export const CATEGORIES = [
  "Tesla",
  "SpaceX",
  "Starship",
  "FSD",
  "Gigafactory",
  "Neuralink",
  "Twitter/X",
  "Elon Personal",
];

export const TESLA_MODELS = [
  "Model S",
  "Model 3",
  "Model X",
  "Model Y",
  "Cybertruck",
  "Roadster",
  "Semi",
  "Cybercab",
  "Not yet",
];

export const TIER_META = {
  Earthbound: { points: 100, key: "ion" },
  Orbit: { points: 200, key: "plasma" },
  Martian: { points: 300, key: "abort" },
};

export const QUESTIONS = [
  { q: "In what year did Martin Eberhard and Marc Tarpenning found the company that became Tesla?", o: ["2001", "2003", "2004", "2006"], a: "2003", d: "Earthbound", c: "Tesla" },
  { q: "When did Elon Musk first invest in Tesla and join as Chairman of the Board?", o: ["2003", "2004", "2006", "2008"], a: "2004", d: "Earthbound", c: "Tesla" },
  { q: "What was the first production vehicle delivered by Tesla?", o: ["Model S", "Roadster", "Model 3", "Model X"], a: "Roadster", d: "Earthbound", c: "Tesla" },
  { q: "In what year did Tesla go public with its IPO on the Nasdaq?", o: ["2008", "2010", "2012", "2013"], a: "2010", d: "Earthbound", c: "Tesla" },
  { q: "What year did Tesla begin deliveries of the Model S?", o: ["2010", "2012", "2014", "2015"], a: "2012", d: "Earthbound", c: "Tesla" },
  { q: "In what year did Tesla begin shipping Autopilot hardware in its vehicles?", o: ["2012", "2014", "2016", "2018"], a: "2014", d: "Orbit", c: "FSD" },
  { q: "In October 2016, Tesla announced all new vehicles would ship with FSD-capable hardware. What sensor change came with it?", o: ["Removal of all cameras", "8 surround cameras for 360° visibility", "Reliance on LiDAR alone", "Ultrasonic sensors alone"], a: "8 surround cameras for 360° visibility", d: "Orbit", c: "FSD" },
  { q: "When did Tesla first release FSD Beta to a limited group of customers?", o: ["2018", "October 2020", "2022", "2024"], a: "October 2020", d: "Orbit", c: "FSD" },
  { q: "FSD version 12 marked a major architectural shift in 2023–2024. What was the primary change?", o: ["Addition of more LiDAR", "End-to-end neural network replacing most explicit C++ code", "Switch to radar-only", "Complete removal of cameras"], a: "End-to-end neural network replacing most explicit C++ code", d: "Martian", c: "FSD" },
  { q: "Where is Tesla's original vehicle factory located (formerly the NUMMI plant)?", o: ["Austin, Texas", "Fremont, California", "Reno, Nevada", "Shanghai"], a: "Fremont, California", d: "Earthbound", c: "Gigafactory" },
  { q: "When did Gigafactory Nevada begin major battery production operations?", o: ["2014", "2016", "2018", "2019"], a: "2016", d: "Orbit", c: "Gigafactory" },
  { q: "Which was Tesla's first Gigafactory outside the United States?", o: ["Berlin", "Shanghai", "Texas", "Mexico"], a: "Shanghai", d: "Earthbound", c: "Gigafactory" },
  { q: "In what year did both Gigafactory Berlin-Brandenburg and Gigafactory Texas begin vehicle production?", o: ["2020", "2021", "2022", "2023"], a: "2022", d: "Orbit", c: "Gigafactory" },
  { q: "SpaceX was founded in which year?", o: ["2001", "2002", "2004", "2006"], a: "2002", d: "Earthbound", c: "SpaceX" },
  { q: "What was the payload on the first Falcon Heavy test flight in February 2018?", o: ["A Starlink satellite", "Elon Musk's personal Tesla Roadster with Starman", "A Dragon capsule", "A weather satellite"], a: "Elon Musk's personal Tesla Roadster with Starman", d: "Earthbound", c: "SpaceX" },
  { q: "What is the primary long-term goal of the Starship program?", o: ["Replacing commercial airliners", "Making life multi-planetary", "Servicing the ISS", "Deploying weather satellites"], a: "Making life multi-planetary", d: "Earthbound", c: "Starship" },
  { q: "By mid-2026, how many integrated Starship flight tests had SpaceX conducted?", o: ["8", "13", "19", "25"], a: "13", d: "Martian", c: "Starship" },
  { q: "What major upper-stage capability did Starship flights in 2025–2026 demonstrate?", o: ["Permanent orbital station", "In-space Raptor engine relight and payload deployment", "Crewed lunar landing", "Interstellar travel"], a: "In-space Raptor engine relight and payload deployment", d: "Orbit", c: "Starship" },
  { q: "Neuralink was co-founded by Elon Musk in which year?", o: ["2014", "2016", "2018", "2020"], a: "2016", d: "Earthbound", c: "Neuralink" },
  { q: "When did Neuralink perform its first human implant?", o: ["2022", "January 2024", "2025", "2023"], a: "January 2024", d: "Orbit", c: "Neuralink" },
  { q: "How many ultra-thin flexible threads does the Neuralink N1 implant use to record brain activity?", o: ["16", "32", "64", "128"], a: "64", d: "Martian", c: "Neuralink" },
  { q: "What is the name of Neuralink's speech restoration clinical trial?", o: ["PRIME", "VOICE", "Blindsight", "CONVOY"], a: "VOICE", d: "Martian", c: "Neuralink" },
  { q: "In what year did Elon Musk complete the acquisition of Twitter?", o: ["2021", "2022", "2023", "2024"], a: "2022", d: "Earthbound", c: "Twitter/X" },
  { q: "What was the agreed purchase price for Twitter in 2022?", o: ["$30 billion", "$44 billion", "$60 billion", "$20 billion"], a: "$44 billion", d: "Earthbound", c: "Twitter/X" },
  { q: "What did Elon Musk rebrand Twitter as after the acquisition?", o: ["Twttr", "X", "MuskNet", "Starlink Social"], a: "X", d: "Earthbound", c: "Twitter/X" },
  { q: "In March 2025, Elon Musk's xAI acquired X in an all-stock deal. What entity then acquired xAI itself in early 2026?", o: ["Tesla", "SpaceX", "Neuralink", "The Boring Company"], a: "SpaceX", d: "Martian", c: "Twitter/X" },
  { q: "In what year did Elon Musk found his tunnel-construction company?", o: ["2014", "2016", "2019", "2021"], a: "2016", d: "Orbit", c: "Elon Personal" },
  { q: "xAI was founded by Elon Musk in which year?", o: ["2021", "2022", "2023", "2024"], a: "2023", d: "Earthbound", c: "Elon Personal" },
  { q: "Tesla unveiled which model in 2016 as its first vehicle targeting a $35,000 starting price?", o: ["Model S", "Model X", "Model 3", "Model Y"], a: "Model 3", d: "Earthbound", c: "Tesla" },
  { q: "Tesla's first quarterly profit as a public company was reported in which year?", o: ["2010", "2013", "2016", "2018"], a: "2013", d: "Orbit", c: "Tesla" },
  { q: "SpaceX's Starbase launch and production site is located in which U.S. state?", o: ["Florida", "Texas", "California", "New Mexico"], a: "Texas", d: "Earthbound", c: "SpaceX" },
  { q: "Gigafactory Shanghai reached 1 million vehicles produced in roughly how many years after opening?", o: ["Less than 3 years", "5 years", "7 years", "10 years"], a: "Less than 3 years", d: "Orbit", c: "Gigafactory" },
  { q: "By July 2026, Tesla had produced approximately how many total vehicles across its factories?", o: ["5 million", "10 million", "15 million", "2 million"], a: "10 million", d: "Martian", c: "Tesla" },
  { q: "Which hardware version introduced significantly higher resolution cameras and a more powerful computer for FSD?", o: ["HW1", "HW2", "HW3", "HW4 / AI4"], a: "HW4 / AI4", d: "Orbit", c: "FSD" },
  { q: "What is the name of Neuralink's implant system used in human trials?", o: ["Link", "N1", "Telepathy Chip", "Cortex"], a: "N1", d: "Orbit", c: "Neuralink" },
  { q: "In which U.S. state is Gigafactory Texas, and Tesla's current global headquarters, located?", o: ["California", "Nevada", "Texas", "New York"], a: "Texas", d: "Earthbound", c: "Gigafactory" },
  { q: "How does SpaceX recover the Super Heavy booster instead of using landing legs?", o: ["Parachute recovery at sea", "Caught by arms on the launch tower", "Runway landing like a plane", "It is not recovered"], a: "Caught by arms on the launch tower", d: "Orbit", c: "Starship" },
  { q: "What is the standard character limit for a post on X for non-subscribers?", o: ["140", "280", "500", "1,000"], a: "280", d: "Earthbound", c: "Twitter/X" },
  { q: "Which company did Tesla acquire in 2016 to expand into solar energy?", o: ["SolarCity", "SunPower", "First Solar", "Enphase"], a: "SolarCity", d: "Orbit", c: "Tesla" },
  { q: "What is the primary focus of Neuralink's Blindsight program?", o: ["Hearing restoration", "Vision restoration by stimulating the visual cortex", "Memory enhancement", "Mood regulation"], a: "Vision restoration by stimulating the visual cortex", d: "Martian", c: "Neuralink" },
  { q: "SpaceX's Starship is designed to be fully reusable. What does this primarily aim to achieve?", o: ["Higher launch costs", "Dramatically lower cost per kilogram to orbit", "Single-use only missions", "Exclusively military use"], a: "Dramatically lower cost per kilogram to orbit", d: "Earthbound", c: "Starship" },
  { q: "In which year did Tesla open its first Supercharger stations?", o: ["2010", "2012", "2015", "2018"], a: "2012", d: "Orbit", c: "Tesla" },
  { q: "What was the original name of the company before it was shortened to just Tesla?", o: ["Tesla Electric", "Tesla Motors", "Electric Cars Inc.", "Musk Motors"], a: "Tesla Motors", d: "Earthbound", c: "Tesla" },
  { q: "Which AI company did Elon Musk co-found in 2015 before later departing its board?", o: ["OpenAI", "DeepMind", "Anthropic", "xAI"], a: "OpenAI", d: "Orbit", c: "Elon Personal" },
  { q: "By mid-2026 reports, cumulative FSD (Supervised) miles driven exceeded approximately what level?", o: ["1 billion", "Several billion", "100 million", "500 million"], a: "Several billion", d: "Martian", c: "FSD" },
  { q: "What year did Cybertruck production and customer deliveries begin at Gigafactory Texas?", o: ["2021", "2022", "2023", "2024"], a: "2023", d: "Orbit", c: "Gigafactory" },
  { q: "Neuralink aims for high-volume production and more automated surgery starting in which year, per its late-2025 announcement?", o: ["2024", "2025", "2026", "2028"], a: "2026", d: "Martian", c: "Neuralink" },
  { q: "Which rocket launched the first commercial crewed mission to the ISS for NASA in 2020?", o: ["Falcon Heavy", "Falcon 9", "Starship", "Falcon 1"], a: "Falcon 9", d: "Orbit", c: "SpaceX" },
  { q: "In the March 2025 xAI–X deal, what was the approximate valuation assigned to X itself?", o: ["$80 billion", "Around $33 billion", "$44 billion", "$12 billion"], a: "Around $33 billion", d: "Martian", c: "Twitter/X" },
  { q: "Tesla's Model Y entered production at which factory first, in 2020?", o: ["Shanghai", "Fremont", "Berlin", "Texas"], a: "Fremont", d: "Orbit", c: "Tesla" },
  { q: "SpaceX's acquisition of xAI in February 2026 combined the companies into an entity with roughly what valuation, ahead of a planned IPO?", o: ["$80 billion", "$500 billion", "$1.25 trillion", "$250 billion"], a: "$1.25 trillion", d: "Martian", c: "Elon Personal" },
  { q: "In 2025, Tesla disclosed an investment in xAI as part of its Series E funding round. Approximately how much did Tesla invest?", o: ["$500 million", "$2 billion", "$10 billion", "$50 million"], a: "$2 billion", d: "Martian", c: "Elon Personal" },
  { q: "By June 2026, Neuralink had reached how many implanted patients, up from 21 confirmed earlier in the year?", o: ["23", "26", "30", "40"], a: "26", d: "Martian", c: "Neuralink" },
  { q: "What is the name of Tesla's humanoid robot program?", o: ["Optimus", "Atlas", "Ares", "Cortex"], a: "Optimus", d: "Earthbound", c: "Elon Personal" },
  { q: "Which Tesla factory began converting part of its production line to build Optimus robots in 2026?", o: ["Fremont", "Gigafactory Texas", "Gigafactory Berlin", "Gigafactory Shanghai"], a: "Fremont", d: "Earthbound", c: "Gigafactory" },
  { q: "What is Tesla's purpose-built robotaxi vehicle called?", o: ["Cybertruck", "Cybercab", "Model R", "Roadtrip"], a: "Cybercab", d: "Earthbound", c: "Tesla" },
  { q: "The Cybercab was designed without which of the following?", o: ["A battery", "A steering wheel and pedals", "Doors", "Wheels"], a: "A steering wheel and pedals", d: "Earthbound", c: "Tesla" },
  { q: "In which Texas city did Tesla first launch its Robotaxi ride-hailing service?", o: ["Dallas", "Houston", "Austin", "San Antonio"], a: "Austin", d: "Earthbound", c: "Tesla" },
  { q: "What does FSD stand for?", o: ["Full Self-Driving", "Fast Systems Design", "Fleet Software Distribution", "Final Safety Diagnostic"], a: "Full Self-Driving", d: "Earthbound", c: "FSD" },
  { q: "Neuralink's first human patient used the implant primarily to control what?", o: ["A computer cursor", "A wheelchair", "A prosthetic leg", "A hearing aid"], a: "A computer cursor", d: "Earthbound", c: "Neuralink" },
  { q: "Which company owns and operates the Starlink satellite internet network?", o: ["Tesla", "SpaceX", "xAI", "The Boring Company"], a: "SpaceX", d: "Earthbound", c: "SpaceX" },
  { q: "What is the name of Elon Musk's tunnel-construction company?", o: ["The Boring Company", "Tunnel Corp", "Digger Inc.", "Underland"], a: "The Boring Company", d: "Earthbound", c: "Elon Personal" },
  { q: "In which country was Elon Musk born?", o: ["South Africa", "Canada", "United States", "Australia"], a: "South Africa", d: "Earthbound", c: "Elon Personal" },
  { q: "What is the name of xAI's chatbot?", o: ["Grok", "Ada", "Nova", "Echo"], a: "Grok", d: "Earthbound", c: "Elon Personal" },
  { q: "Which Tesla vehicle line ended production in 2026 after more than a decade on the market?", o: ["Model 3", "Model Y", "Model S and Model X", "Cybertruck"], a: "Model S and Model X", d: "Earthbound", c: "Tesla" },
  { q: "Roughly how many unique parts does Tesla's Optimus robot have, according to Elon Musk?", o: ["About 1,000", "About 10,000", "About 100,000", "About 500"], a: "About 10,000", d: "Orbit", c: "Elon Personal" },
  { q: "What long-term annual production capacity is Tesla designing its second Optimus line at Gigafactory Texas for?", o: ["100,000 robots", "1 million robots", "10 million robots", "500,000 robots"], a: "10 million robots", d: "Orbit", c: "Gigafactory" },
  { q: "Which generation of Optimus is the first designed for mass production?", o: ["Gen 1", "Gen 2", "Gen 3", "Gen 4"], a: "Gen 3", d: "Orbit", c: "Elon Personal" },
  { q: "Which Tesla model was the first built at Gigafactory Berlin-Brandenburg?", o: ["Model 3", "Model Y", "Model S", "Cybertruck"], a: "Model Y", d: "Orbit", c: "Tesla" },
  { q: "Which Florida city hosted Tesla's first Robotaxi service outside Texas and California?", o: ["Orlando", "Tampa", "Miami", "Jacksonville"], a: "Miami", d: "Orbit", c: "Tesla" },
  { q: "What upcoming FSD architecture is planned to scale the driving model roughly tenfold in parameter count?", o: ["FSD v12", "FSD v13", "FSD v14", "FSD v15"], a: "FSD v15", d: "Orbit", c: "FSD" },
  { q: "How many electrodes does the Neuralink N1 implant used in human trials have?", o: ["256", "1,024", "3,072", "10,000"], a: "1,024", d: "Orbit", c: "Neuralink" },
  { q: "What surgical innovation is Neuralink using to help scale up the number of implant procedures it can perform?", o: ["A remote-controlled scalpel", "A dedicated surgical robot", "Fully manual surgery only", "3D-printed skull plates"], a: "A dedicated surgical robot", d: "Orbit", c: "Neuralink" },
  { q: "Starship's 13th flight test in July 2026 achieved a first for which product line?", o: ["Deployment of next-generation Starlink V3 satellites", "First crewed flight", "First Mars flyby", "First flight without Super Heavy"], a: "Deployment of next-generation Starlink V3 satellites", d: "Orbit", c: "Starship" },
  { q: "What nickname did SpaceX employees give Starship's 13th flight test?", o: ["Lucky 13", "The Big One", "Ironclad", "Final Countdown"], a: "Lucky 13", d: "Orbit", c: "Starship" },
  { q: "Starship's 13th flight test splashed down in which ocean?", o: ["Atlantic Ocean", "Pacific Ocean", "Indian Ocean", "Arctic Ocean"], a: "Indian Ocean", d: "Orbit", c: "Starship" },
  { q: "What generation of Super Heavy-Starship vehicle flew for the first time on Flight 12 in May 2026?", o: ["V1", "V2", "V3", "V4"], a: "V3", d: "Orbit", c: "Starship" },
  { q: "What major corporate event did SpaceX complete shortly before Starship's 13th flight test in 2026?", o: ["A merger with Tesla", "An initial public offering (IPO)", "A bankruptcy filing", "A move to a new headquarters"], a: "An initial public offering (IPO)", d: "Orbit", c: "SpaceX" },
  { q: "What is the diameter of the Neuralink N1 implant, roughly comparable to the size of a coin?", o: ["About 10 mm", "About 23 mm", "About 50 mm", "About 5 mm"], a: "About 23 mm", d: "Orbit", c: "Neuralink" },
  { q: "What consumer-facing product name did Neuralink give its first brain-computer interface?", o: ["Telepathy", "Mindlink", "Synapse", "Cortex"], a: "Telepathy", d: "Orbit", c: "Neuralink" },
  { q: "What is the name of the surgical robot Neuralink built to insert its implant threads?", o: ["R1", "N1", "V1", "Mechazilla"], a: "R1", d: "Orbit", c: "Neuralink" },
  { q: "Roughly how many total vehicles had the Tesla Model S and Model X produced combined by the end of their run?", o: ["Around 100,000", "Around 300,000", "Over 600,000", "Over 2 million"], a: "Over 600,000", d: "Orbit", c: "Tesla" },
  { q: "What price point has Tesla targeted for the Cybercab to sell under?", o: ["$20,000", "$25,000", "$30,000", "$40,000"], a: "$30,000", d: "Orbit", c: "Tesla" },
  { q: "Where did the first production Cybercab roll off the assembly line in early 2026?", o: ["Fremont", "Gigafactory Texas", "Gigafactory Nevada", "Gigafactory Berlin"], a: "Gigafactory Texas", d: "Orbit", c: "Gigafactory" },
  { q: "Elon Musk earned undergraduate degrees in physics and economics from which university?", o: ["Stanford", "University of Pennsylvania", "MIT", "Queen's University"], a: "University of Pennsylvania", d: "Orbit", c: "Elon Personal" },
  { q: "How many Raptor engines power the Super Heavy booster on a full Starship stack?", o: ["9", "20", "33", "44"], a: "33", d: "Martian", c: "Starship" },
  { q: "What is the name of the launch tower system SpaceX uses to catch the Super Heavy booster during landing?", o: ["Mechazilla", "Ironclad", "Titan Arm", "Catchframe"], a: "Mechazilla", d: "Martian", c: "Starship" },
  { q: "What key structural test did Starship's 12th flight perform on its rear flaps during reentry?", o: ["A cooling system test", "An intentional stress test of structural limits", "A repainting test", "A camera calibration test"], a: "An intentional stress test of structural limits", d: "Martian", c: "Starship" },
  { q: "What raw material processing does Tesla now perform in Texas to support battery production, beyond cell assembly?", o: ["Cathode material production and lithium refining", "Rubber tire manufacturing", "Glass tempering only", "Steel smelting"], a: "Cathode material production and lithium refining", d: "Martian", c: "Gigafactory" },
  { q: "Approximately how much operating cash flow did Tesla report for Q1 2026?", o: ["$1.2 billion", "$3.9 billion", "$8 billion", "$500 million"], a: "$3.9 billion", d: "Martian", c: "Tesla" },
  { q: "What GAAP gross margin did Tesla report alongside its Q1 2026 operating cash flow figures?", o: ["9%", "15%", "21%", "35%"], a: "21%", d: "Martian", c: "Tesla" },
  { q: "What new processor is Tesla developing to support Optimus and vehicle autonomy compute needs?", o: ["AI5", "M4", "Cortex Prime", "Dojo 3"], a: "AI5", d: "Martian", c: "Elon Personal" },
  { q: "What is the approximate manufacturing cost Neuralink cited for its newer surgical robots, down from $10–20 million for earlier versions?", o: ["$50,000", "$500,000", "$2 million", "$5 million"], a: "$500,000", d: "Martian", c: "Neuralink" },
  { q: "In which four countries had Neuralink's PRIME Study enrolled patients as of 2026?", o: ["US, Canada, UK, UAE", "US, Germany, Japan, Australia", "US, Mexico, Brazil, UK", "US, China, India, UAE"], a: "US, Canada, UK, UAE", d: "Martian", c: "Neuralink" },
  { q: "How many patients were enrolled in Neuralink's GB PRIME study in Great Britain as of May 2026?", o: ["Two", "Seven", "Fifteen", "Twenty"], a: "Seven", d: "Martian", c: "Neuralink" },
  { q: "What size battery capacity was Tesla targeting for Phase 1 of a training-data energy system tied to Optimus development, expected online in April 2026?", o: ["50 MW", "100 MW", "250 MW", "500 MW"], a: "250 MW", d: "Martian", c: "Elon Personal" },
  { q: "Tesla's 4680 battery cell is named after its dimensions. What are they?", o: ["40mm x 68mm", "46mm x 80mm", "48mm x 60mm", "44mm x 68mm"], a: "46mm x 80mm", d: "Martian", c: "Tesla" },
  { q: "What cell type is Tesla increasing production of to support Cybercab and Tesla Semi ramps?", o: ["18650", "2170", "4680", "21700-XL"], a: "4680", d: "Martian", c: "Gigafactory" },
  { q: "The tri-motor Tesla Model S Plaid produces approximately how much peak horsepower?", o: ["760 hp", "1,020 hp", "1,340 hp", "620 hp"], a: "1,020 hp", d: "Martian", c: "Tesla" },
  { q: "How many years was the Tesla Model S in production before the line ended in 2026?", o: ["8 years", "11 years", "14 years", "18 years"], a: "14 years", d: "Martian", c: "Tesla" },
  { q: "How many years was the Tesla Model X in production before its line ended in 2026?", o: ["6 years", "8 years", "11 years", "14 years"], a: "11 years", d: "Martian", c: "Tesla" },
  { q: "Tesla's first Florida Robotaxi service launched with a geofenced area of roughly what size?", o: ["1–3 sq mi", "10–14 sq mi", "50 sq mi", "100 sq mi"], a: "10–14 sq mi", d: "Martian", c: "Tesla" },
  { q: "What communications technology did Tesla integrate into Cybercab robotaxi vehicles, benefiting SpaceX as well?", o: ["Starlink connectivity", "5G-only modems", "Ham radio", "Bluetooth mesh networking"], a: "Starlink connectivity", d: "Martian", c: "Tesla" },
];
