export const CATEGORIES = [
  "Tesla",
  "SpaceX",
  "Starship",
  "FSD",
  "Gigafactory",
  "Neuralink",
  "Twitter/X",
  "Elon Personal",
  "NASA",
  "Deep Space",
  "Commercial Space",
  "Planetary Science",
  "ESA",
  "Telescopes",
  "Astronauts",
  "Physics",
];

export const TESLA_MODELS = [
  "Model S",
  "Model 3",
  "Model X",
  "Model Y",
  "Cybertruck",
  "Roadster",
  "Semi",
  "Cybercab",
  "Not yet",
];

export const TIER_META = {
  Earthbound: { points: 100, key: "ion" },
  Orbit: { points: 200, key: "plasma" },
  Martian: { points: 300, key: "abort" },
};

/* Each question: q (prompt), o (4 options), a (correct option, must match
   one of o exactly), d (difficulty tier — Earthbound/Orbit/Martian, keys
   into TIER_META above), c (category, must be listed in CATEGORIES above).
   insight is optional: a 1-2 sentence "why it matters" fact shown after
   answering (see components/Game.jsx) — most questions don't have one yet,
   and the UI treats its absence as normal. */
export const QUESTIONS = [
  { q: "In what year did Martin Eberhard and Marc Tarpenning found the company that became Tesla?", o: ["2001", "2003", "2004", "2006"], a: "2003", d: "Earthbound", c: "Tesla" },
  { q: "When did Elon Musk first invest in Tesla and join as Chairman of the Board?", o: ["2003", "2004", "2006", "2008"], a: "2004", d: "Earthbound", c: "Tesla" },
  { q: "What was the first production vehicle delivered by Tesla?", o: ["Model S", "Roadster", "Model 3", "Model X"], a: "Roadster", d: "Earthbound", c: "Tesla" },
  { q: "In what year did Tesla go public with its IPO on the Nasdaq?", o: ["2008", "2010", "2012", "2013"], a: "2010", d: "Earthbound", c: "Tesla" },
  { q: "What year did Tesla begin deliveries of the Model S?", o: ["2010", "2012", "2014", "2015"], a: "2012", d: "Earthbound", c: "Tesla" },
  { q: "In what year did Tesla begin shipping Autopilot hardware in its vehicles?", o: ["2012", "2014", "2016", "2018"], a: "2014", d: "Orbit", c: "FSD" },
  { q: "In October 2016, Tesla announced all new vehicles would ship with FSD-capable hardware. What sensor change came with it?", o: ["Removal of all cameras", "8 surround cameras for 360° visibility", "Reliance on LiDAR alone", "Ultrasonic sensors alone"], a: "8 surround cameras for 360° visibility", d: "Orbit", c: "FSD" },
  { q: "When did Tesla first release FSD Beta to a limited group of customers?", o: ["2018", "October 2020", "2022", "2024"], a: "October 2020", d: "Orbit", c: "FSD" },
  { q: "FSD version 12 marked a major architectural shift in 2023–2024. What was the primary change?", o: ["Addition of more LiDAR", "End-to-end neural network replacing most explicit C++ code", "Switch to radar-only", "Complete removal of cameras"], a: "End-to-end neural network replacing most explicit C++ code", d: "Martian", c: "FSD" },
  { q: "Where is Tesla's original vehicle factory located (formerly the NUMMI plant)?", o: ["Austin, Texas", "Fremont, California", "Reno, Nevada", "Shanghai"], a: "Fremont, California", d: "Earthbound", c: "Gigafactory" },
  { q: "When did Gigafactory Nevada begin major battery production operations?", o: ["2014", "2016", "2018", "2019"], a: "2016", d: "Orbit", c: "Gigafactory" },
  { q: "Which was Tesla's first Gigafactory outside the United States?", o: ["Berlin", "Shanghai", "Texas", "Mexico"], a: "Shanghai", d: "Earthbound", c: "Gigafactory" },
  { q: "In what year did both Gigafactory Berlin-Brandenburg and Gigafactory Texas begin vehicle production?", o: ["2020", "2021", "2022", "2023"], a: "2022", d: "Orbit", c: "Gigafactory" },
  { q: "SpaceX was founded in which year?", o: ["2001", "2002", "2004", "2006"], a: "2002", d: "Earthbound", c: "SpaceX" },
  { q: "What was the payload on the first Falcon Heavy test flight in February 2018?", o: ["A Starlink satellite", "Elon Musk's personal Tesla Roadster with Starman", "A Dragon capsule", "A weather satellite"], a: "Elon Musk's personal Tesla Roadster with Starman", d: "Earthbound", c: "SpaceX" },
  { q: "What is the primary long-term goal of the Starship program?", o: ["Replacing commercial airliners", "Making life multi-planetary", "Servicing the ISS", "Deploying weather satellites"], a: "Making life multi-planetary", d: "Earthbound", c: "Starship" },
  { q: "By mid-2026, how many integrated Starship flight tests had SpaceX conducted?", o: ["8", "13", "19", "25"], a: "13", d: "Martian", c: "Starship" },
  { q: "What major upper-stage capability did Starship flights in 2025–2026 demonstrate?", o: ["Permanent orbital station", "In-space Raptor engine relight and payload deployment", "Crewed lunar landing", "Interstellar travel"], a: "In-space Raptor engine relight and payload deployment", d: "Orbit", c: "Starship" },
  { q: "Neuralink was co-founded by Elon Musk in which year?", o: ["2014", "2016", "2018", "2020"], a: "2016", d: "Earthbound", c: "Neuralink" },
  { q: "When did Neuralink perform its first human implant?", o: ["2022", "January 2024", "2025", "2023"], a: "January 2024", d: "Orbit", c: "Neuralink" },
  { q: "How many ultra-thin flexible threads does the Neuralink N1 implant use to record brain activity?", o: ["16", "32", "64", "128"], a: "64", d: "Martian", c: "Neuralink" },
  { q: "What is the name of Neuralink's speech restoration clinical trial?", o: ["PRIME", "VOICE", "Blindsight", "CONVOY"], a: "VOICE", d: "Martian", c: "Neuralink" },
  { q: "In what year did Elon Musk complete the acquisition of Twitter?", o: ["2021", "2022", "2023", "2024"], a: "2022", d: "Earthbound", c: "Twitter/X" },
  { q: "What was the agreed purchase price for Twitter in 2022?", o: ["$30 billion", "$44 billion", "$60 billion", "$20 billion"], a: "$44 billion", d: "Earthbound", c: "Twitter/X" },
  { q: "What did Elon Musk rebrand Twitter as after the acquisition?", o: ["Twttr", "X", "MuskNet", "Starlink Social"], a: "X", d: "Earthbound", c: "Twitter/X" },
  { q: "In March 2025, Elon Musk's xAI acquired X in an all-stock deal. What entity then acquired xAI itself in early 2026?", o: ["Tesla", "SpaceX", "Neuralink", "The Boring Company"], a: "SpaceX", d: "Martian", c: "Twitter/X" },
  { q: "In what year did Elon Musk found his tunnel-construction company?", o: ["2014", "2016", "2019", "2021"], a: "2016", d: "Orbit", c: "Elon Personal" },
  { q: "xAI was founded by Elon Musk in which year?", o: ["2021", "2022", "2023", "2024"], a: "2023", d: "Earthbound", c: "Elon Personal" },
  { q: "Tesla unveiled which model in 2016 as its first vehicle targeting a $35,000 starting price?", o: ["Model S", "Model X", "Model 3", "Model Y"], a: "Model 3", d: "Earthbound", c: "Tesla" },
  { q: "Tesla's first quarterly profit as a public company was reported in which year?", o: ["2010", "2013", "2016", "2018"], a: "2013", d: "Orbit", c: "Tesla" },
  { q: "SpaceX's Starbase launch and production site is located in which U.S. state?", o: ["Florida", "Texas", "California", "New Mexico"], a: "Texas", d: "Earthbound", c: "SpaceX" },
  { q: "Gigafactory Shanghai reached 1 million vehicles produced in roughly how many years after opening?", o: ["Less than 3 years", "5 years", "7 years", "10 years"], a: "Less than 3 years", d: "Orbit", c: "Gigafactory" },
  { q: "By July 2026, Tesla had produced approximately how many total vehicles across its factories?", o: ["5 million", "10 million", "15 million", "2 million"], a: "10 million", d: "Martian", c: "Tesla" },
  { q: "Which hardware version introduced significantly higher resolution cameras and a more powerful computer for FSD?", o: ["HW1", "HW2", "HW3", "HW4 / AI4"], a: "HW4 / AI4", d: "Orbit", c: "FSD" },
  { q: "What is the name of Neuralink's implant system used in human trials?", o: ["Link", "N1", "Telepathy Chip", "Cortex"], a: "N1", d: "Orbit", c: "Neuralink" },
  { q: "In which U.S. state is Gigafactory Texas, and Tesla's current global headquarters, located?", o: ["California", "Nevada", "Texas", "New York"], a: "Texas", d: "Earthbound", c: "Gigafactory" },
  { q: "How does SpaceX recover the Super Heavy booster instead of using landing legs?", o: ["Parachute recovery at sea", "Caught by arms on the launch tower", "Runway landing like a plane", "It is not recovered"], a: "Caught by arms on the launch tower", d: "Orbit", c: "Starship" },
  { q: "What is the standard character limit for a post on X for non-subscribers?", o: ["140", "280", "500", "1,000"], a: "280", d: "Earthbound", c: "Twitter/X" },
  { q: "Which company did Tesla acquire in 2016 to expand into solar energy?", o: ["SolarCity", "SunPower", "First Solar", "Enphase"], a: "SolarCity", d: "Orbit", c: "Tesla" },
  { q: "What is the primary focus of Neuralink's Blindsight program?", o: ["Hearing restoration", "Vision restoration by stimulating the visual cortex", "Memory enhancement", "Mood regulation"], a: "Vision restoration by stimulating the visual cortex", d: "Martian", c: "Neuralink" },
  { q: "SpaceX's Starship is designed to be fully reusable. What does this primarily aim to achieve?", o: ["Higher launch costs", "Dramatically lower cost per kilogram to orbit", "Single-use only missions", "Exclusively military use"], a: "Dramatically lower cost per kilogram to orbit", d: "Earthbound", c: "Starship" },
  { q: "In which year did Tesla open its first Supercharger stations?", o: ["2010", "2012", "2015", "2018"], a: "2012", d: "Orbit", c: "Tesla" },
  { q: "What was the original name of the company before it was shortened to just Tesla?", o: ["Tesla Electric", "Tesla Motors", "Electric Cars Inc.", "Musk Motors"], a: "Tesla Motors", d: "Earthbound", c: "Tesla" },
  { q: "Which AI company did Elon Musk co-found in 2015 before later departing its board?", o: ["OpenAI", "DeepMind", "Anthropic", "xAI"], a: "OpenAI", d: "Orbit", c: "Elon Personal" },
  { q: "By mid-2026 reports, cumulative FSD (Supervised) miles driven exceeded approximately what level?", o: ["1 billion", "Several billion", "100 million", "500 million"], a: "Several billion", d: "Martian", c: "FSD" },
  { q: "What year did Cybertruck production and customer deliveries begin at Gigafactory Texas?", o: ["2021", "2022", "2023", "2024"], a: "2023", d: "Orbit", c: "Gigafactory" },
  { q: "Neuralink aims for high-volume production and more automated surgery starting in which year, per its late-2025 announcement?", o: ["2024", "2025", "2026", "2028"], a: "2026", d: "Martian", c: "Neuralink" },
  { q: "Which rocket launched the first commercial crewed mission to the ISS for NASA in 2020?", o: ["Falcon Heavy", "Falcon 9", "Starship", "Falcon 1"], a: "Falcon 9", d: "Orbit", c: "SpaceX" },
  { q: "In the March 2025 xAI–X deal, what was the approximate valuation assigned to X itself?", o: ["$80 billion", "Around $33 billion", "$44 billion", "$12 billion"], a: "Around $33 billion", d: "Martian", c: "Twitter/X" },
  { q: "Tesla's Model Y entered production at which factory first, in 2020?", o: ["Shanghai", "Fremont", "Berlin", "Texas"], a: "Fremont", d: "Orbit", c: "Tesla" },
  { q: "SpaceX's acquisition of xAI in February 2026 combined the companies into an entity with roughly what valuation, ahead of a planned IPO?", o: ["$80 billion", "$500 billion", "$1.25 trillion", "$250 billion"], a: "$1.25 trillion", d: "Martian", c: "Elon Personal" },
  { q: "In 2025, Tesla disclosed an investment in xAI as part of its Series E funding round. Approximately how much did Tesla invest?", o: ["$500 million", "$2 billion", "$10 billion", "$50 million"], a: "$2 billion", d: "Martian", c: "Elon Personal" },
  { q: "By June 2026, Neuralink had reached how many implanted patients, up from 21 confirmed earlier in the year?", o: ["23", "26", "30", "40"], a: "26", d: "Martian", c: "Neuralink" },
  { q: "What is the name of Tesla's humanoid robot program?", o: ["Optimus", "Atlas", "Ares", "Cortex"], a: "Optimus", d: "Earthbound", c: "Elon Personal" },
  { q: "Which Tesla factory began converting part of its production line to build Optimus robots in 2026?", o: ["Fremont", "Gigafactory Texas", "Gigafactory Berlin", "Gigafactory Shanghai"], a: "Fremont", d: "Earthbound", c: "Gigafactory" },
  { q: "What is Tesla's purpose-built robotaxi vehicle called?", o: ["Cybertruck", "Cybercab", "Model R", "Roadtrip"], a: "Cybercab", d: "Earthbound", c: "Tesla" },
  { q: "The Cybercab was designed without which of the following?", o: ["A battery", "A steering wheel and pedals", "Doors", "Wheels"], a: "A steering wheel and pedals", d: "Earthbound", c: "Tesla" },
  { q: "In which Texas city did Tesla first launch its Robotaxi ride-hailing service?", o: ["Dallas", "Houston", "Austin", "San Antonio"], a: "Austin", d: "Earthbound", c: "Tesla" },
  { q: "What does FSD stand for?", o: ["Full Self-Driving", "Fast Systems Design", "Fleet Software Distribution", "Final Safety Diagnostic"], a: "Full Self-Driving", d: "Earthbound", c: "FSD" },
  { q: "Neuralink's first human patient used the implant primarily to control what?", o: ["A computer cursor", "A wheelchair", "A prosthetic leg", "A hearing aid"], a: "A computer cursor", d: "Earthbound", c: "Neuralink" },
  { q: "Which company owns and operates the Starlink satellite internet network?", o: ["Tesla", "SpaceX", "xAI", "The Boring Company"], a: "SpaceX", d: "Earthbound", c: "SpaceX" },
  { q: "What is the name of Elon Musk's tunnel-construction company?", o: ["The Boring Company", "Tunnel Corp", "Digger Inc.", "Underland"], a: "The Boring Company", d: "Earthbound", c: "Elon Personal" },
  { q: "In which country was Elon Musk born?", o: ["South Africa", "Canada", "United States", "Australia"], a: "South Africa", d: "Earthbound", c: "Elon Personal" },
  { q: "What is the name of xAI's chatbot?", o: ["Grok", "Ada", "Nova", "Echo"], a: "Grok", d: "Earthbound", c: "Elon Personal" },
  { q: "Which Tesla vehicle line ended production in 2026 after more than a decade on the market?", o: ["Model 3", "Model Y", "Model S and Model X", "Cybertruck"], a: "Model S and Model X", d: "Earthbound", c: "Tesla" },
  { q: "Roughly how many unique parts does Tesla's Optimus robot have, according to Elon Musk?", o: ["About 1,000", "About 10,000", "About 100,000", "About 500"], a: "About 10,000", d: "Orbit", c: "Elon Personal" },
  { q: "What long-term annual production capacity is Tesla designing its second Optimus line at Gigafactory Texas for?", o: ["100,000 robots", "1 million robots", "10 million robots", "500,000 robots"], a: "10 million robots", d: "Orbit", c: "Gigafactory" },
  { q: "Which generation of Optimus is the first designed for mass production?", o: ["Gen 1", "Gen 2", "Gen 3", "Gen 4"], a: "Gen 3", d: "Orbit", c: "Elon Personal" },
  { q: "Which Tesla model was the first built at Gigafactory Berlin-Brandenburg?", o: ["Model 3", "Model Y", "Model S", "Cybertruck"], a: "Model Y", d: "Orbit", c: "Tesla" },
  { q: "Which Florida city hosted Tesla's first Robotaxi service outside Texas and California?", o: ["Orlando", "Tampa", "Miami", "Jacksonville"], a: "Miami", d: "Orbit", c: "Tesla" },
  { q: "What upcoming FSD architecture is planned to scale the driving model roughly tenfold in parameter count?", o: ["FSD v12", "FSD v13", "FSD v14", "FSD v15"], a: "FSD v15", d: "Orbit", c: "FSD" },
  { q: "How many electrodes does the Neuralink N1 implant used in human trials have?", o: ["256", "1,024", "3,072", "10,000"], a: "1,024", d: "Orbit", c: "Neuralink" },
  { q: "What surgical innovation is Neuralink using to help scale up the number of implant procedures it can perform?", o: ["A remote-controlled scalpel", "A dedicated surgical robot", "Fully manual surgery only", "3D-printed skull plates"], a: "A dedicated surgical robot", d: "Orbit", c: "Neuralink" },
  { q: "Starship's 13th flight test in July 2026 achieved a first for which product line?", o: ["Deployment of next-generation Starlink V3 satellites", "First crewed flight", "First Mars flyby", "First flight without Super Heavy"], a: "Deployment of next-generation Starlink V3 satellites", d: "Orbit", c: "Starship" },
  { q: "What nickname did SpaceX employees give Starship's 13th flight test?", o: ["Lucky 13", "The Big One", "Ironclad", "Final Countdown"], a: "Lucky 13", d: "Orbit", c: "Starship" },
  { q: "Starship's 13th flight test splashed down in which ocean?", o: ["Atlantic Ocean", "Pacific Ocean", "Indian Ocean", "Arctic Ocean"], a: "Indian Ocean", d: "Orbit", c: "Starship" },
  { q: "What generation of Super Heavy-Starship vehicle flew for the first time on Flight 12 in May 2026?", o: ["V1", "V2", "V3", "V4"], a: "V3", d: "Orbit", c: "Starship" },
  { q: "What major corporate event did SpaceX complete shortly before Starship's 13th flight test in 2026?", o: ["A merger with Tesla", "An initial public offering (IPO)", "A bankruptcy filing", "A move to a new headquarters"], a: "An initial public offering (IPO)", d: "Orbit", c: "SpaceX" },
  { q: "What is the diameter of the Neuralink N1 implant, roughly comparable to the size of a coin?", o: ["About 10 mm", "About 23 mm", "About 50 mm", "About 5 mm"], a: "About 23 mm", d: "Orbit", c: "Neuralink" },
  { q: "What consumer-facing product name did Neuralink give its first brain-computer interface?", o: ["Telepathy", "Mindlink", "Synapse", "Cortex"], a: "Telepathy", d: "Orbit", c: "Neuralink" },
  { q: "What is the name of the surgical robot Neuralink built to insert its implant threads?", o: ["R1", "N1", "V1", "Mechazilla"], a: "R1", d: "Orbit", c: "Neuralink" },
  { q: "Roughly how many total vehicles had the Tesla Model S and Model X produced combined by the end of their run?", o: ["Around 100,000", "Around 300,000", "Over 600,000", "Over 2 million"], a: "Over 600,000", d: "Orbit", c: "Tesla" },
  { q: "What price point has Tesla targeted for the Cybercab to sell under?", o: ["$20,000", "$25,000", "$30,000", "$40,000"], a: "$30,000", d: "Orbit", c: "Tesla" },
  { q: "Where did the first production Cybercab roll off the assembly line in early 2026?", o: ["Fremont", "Gigafactory Texas", "Gigafactory Nevada", "Gigafactory Berlin"], a: "Gigafactory Texas", d: "Orbit", c: "Gigafactory" },
  { q: "Elon Musk earned undergraduate degrees in physics and economics from which university?", o: ["Stanford", "University of Pennsylvania", "MIT", "Queen's University"], a: "University of Pennsylvania", d: "Orbit", c: "Elon Personal" },
  { q: "How many Raptor engines power the Super Heavy booster on a full Starship stack?", o: ["9", "20", "33", "44"], a: "33", d: "Martian", c: "Starship" },
  { q: "What is the name of the launch tower system SpaceX uses to catch the Super Heavy booster during landing?", o: ["Mechazilla", "Ironclad", "Titan Arm", "Catchframe"], a: "Mechazilla", d: "Martian", c: "Starship" },
  { q: "What key structural test did Starship's 12th flight perform on its rear flaps during reentry?", o: ["A cooling system test", "An intentional stress test of structural limits", "A repainting test", "A camera calibration test"], a: "An intentional stress test of structural limits", d: "Martian", c: "Starship" },
  { q: "What raw material processing does Tesla now perform in Texas to support battery production, beyond cell assembly?", o: ["Cathode material production and lithium refining", "Rubber tire manufacturing", "Glass tempering only", "Steel smelting"], a: "Cathode material production and lithium refining", d: "Martian", c: "Gigafactory" },
  { q: "Approximately how much operating cash flow did Tesla report for Q1 2026?", o: ["$1.2 billion", "$3.9 billion", "$8 billion", "$500 million"], a: "$3.9 billion", d: "Martian", c: "Tesla" },
  { q: "What GAAP gross margin did Tesla report alongside its Q1 2026 operating cash flow figures?", o: ["9%", "15%", "21%", "35%"], a: "21%", d: "Martian", c: "Tesla" },
  { q: "What new processor is Tesla developing to support Optimus and vehicle autonomy compute needs?", o: ["AI5", "M4", "Cortex Prime", "Dojo 3"], a: "AI5", d: "Martian", c: "Elon Personal" },
  { q: "What is the approximate manufacturing cost Neuralink cited for its newer surgical robots, down from $10–20 million for earlier versions?", o: ["$50,000", "$500,000", "$2 million", "$5 million"], a: "$500,000", d: "Martian", c: "Neuralink" },
  { q: "In which four countries had Neuralink's PRIME Study enrolled patients as of 2026?", o: ["US, Canada, UK, UAE", "US, Germany, Japan, Australia", "US, Mexico, Brazil, UK", "US, China, India, UAE"], a: "US, Canada, UK, UAE", d: "Martian", c: "Neuralink" },
  { q: "How many patients were enrolled in Neuralink's GB PRIME study in Great Britain as of May 2026?", o: ["Two", "Seven", "Fifteen", "Twenty"], a: "Seven", d: "Martian", c: "Neuralink" },
  { q: "What size battery capacity was Tesla targeting for Phase 1 of a training-data energy system tied to Optimus development, expected online in April 2026?", o: ["50 MW", "100 MW", "250 MW", "500 MW"], a: "250 MW", d: "Martian", c: "Elon Personal" },
  { q: "Tesla's 4680 battery cell is named after its dimensions. What are they?", o: ["40mm x 68mm", "46mm x 80mm", "48mm x 60mm", "44mm x 68mm"], a: "46mm x 80mm", d: "Martian", c: "Tesla" },
  { q: "What cell type is Tesla increasing production of to support Cybercab and Tesla Semi ramps?", o: ["18650", "2170", "4680", "21700-XL"], a: "4680", d: "Martian", c: "Gigafactory" },
  { q: "The tri-motor Tesla Model S Plaid produces approximately how much peak horsepower?", o: ["760 hp", "1,020 hp", "1,340 hp", "620 hp"], a: "1,020 hp", d: "Martian", c: "Tesla" },
  { q: "How many years was the Tesla Model S in production before the line ended in 2026?", o: ["8 years", "11 years", "14 years", "18 years"], a: "14 years", d: "Martian", c: "Tesla" },
  { q: "How many years was the Tesla Model X in production before its line ended in 2026?", o: ["6 years", "8 years", "11 years", "14 years"], a: "11 years", d: "Martian", c: "Tesla" },
  { q: "Tesla's first Florida Robotaxi service launched with a geofenced area of roughly what size?", o: ["1–3 sq mi", "10–14 sq mi", "50 sq mi", "100 sq mi"], a: "10–14 sq mi", d: "Martian", c: "Tesla" },
  { q: "What communications technology did Tesla integrate into Cybercab robotaxi vehicles, benefiting SpaceX as well?", o: ["Starlink connectivity", "5G-only modems", "Ham radio", "Bluetooth mesh networking"], a: "Starlink connectivity", d: "Martian", c: "Tesla" },

  // ========== NASA ==========

  // Earthbound
  { q: "What does the Artemis program primarily aim to achieve?", o: ["Establish a permanent Mars base", "Return humans to the Moon and establish a sustained presence", "Build a space elevator", "Colonize asteroids"], a: "Return humans to the Moon and establish a sustained presence", d: "Earthbound", c: "NASA", insight: "Artemis isn't a repeat of Apollo — the goal is a reusable, sustainable presence at the lunar south pole that doubles as a proving ground for the much longer trip to Mars." },
  { q: "Which rocket launches the Orion spacecraft for Artemis missions?", o: ["Falcon Heavy", "Space Launch System (SLS)", "New Glenn", "Vulcan Centaur"], a: "Space Launch System (SLS)", d: "Earthbound", c: "NASA", insight: "SLS generates more thrust at liftoff than the Saturn V did — making it, on paper, the most powerful rocket NASA has ever flown." },
  { q: "What is the name of NASA's spacecraft that carries crew on Artemis missions?", o: ["Dragon", "Starliner", "Orion", "Dream Chaser"], a: "Orion", d: "Earthbound", c: "NASA", insight: "Coming back from the Moon, Orion has to survive re-entry at nearly 25,000 mph — roughly 1.5 times faster than a capsule returning from the ISS." },
  { q: "Artemis II, the first crewed Artemis mission, launched in which month of 2026?", o: ["January", "April", "July", "October"], a: "April", d: "Earthbound", c: "NASA", insight: "Artemis II was the first crewed mission to leave low Earth orbit since Apollo 17 in 1972 — over half a century without a human traveling past the Van Allen belts." },
  { q: "Which NASA rover is currently collecting and caching rock samples on Mars for eventual return to Earth?", o: ["Curiosity", "Perseverance", "Opportunity", "Spirit"], a: "Perseverance", d: "Earthbound", c: "NASA", insight: "Perseverance seals its samples in titanium tubes and leaves them on the surface for a future mission to collect — no spacecraft has ever launched off another planet and brought material back to Earth." },
  { q: "What is the name of NASA's flagship infrared space telescope that succeeded Hubble in many deep-space observations?", o: ["Chandra", "Spitzer", "James Webb Space Telescope", "Kepler"], a: "James Webb Space Telescope", d: "Earthbound", c: "NASA", insight: "Webb sees in infrared rather than visible light so it can look straight through dust clouds and catch galaxies so distant their light has been stretched beyond the visible spectrum entirely." },
  { q: "NASA's Commercial Crew Program currently uses which two vehicles to send astronauts to the ISS?", o: ["Orion and Starliner", "Dragon and Starliner", "Dragon and New Shepard", "Orion and Dragon"], a: "Dragon and Starliner", d: "Earthbound", c: "NASA", insight: "Commercial Crew ended nearly a decade of NASA depending entirely on Russian Soyuz seats to reach the ISS after the Space Shuttle retired in 2011." },
  { q: "Where is NASA's primary human spaceflight launch site for Artemis located?", o: ["Vandenberg Space Force Base", "Kennedy Space Center, Florida", "Wallops Flight Facility", "Stennis Space Center"], a: "Kennedy Space Center, Florida", d: "Earthbound", c: "NASA", insight: "Kennedy sits on Florida's coast so spent rocket stages fall over open ocean instead of populated land, and launching eastward lets a rocket ride a free boost from Earth's own rotation." },
  { q: "What is the name of the joint NASA-ISRO Earth-observing radar satellite launched in 2025?", o: ["NISAR", "SPHEREx", "PACE", "SWOT"], a: "NISAR", d: "Earthbound", c: "NASA", insight: "NISAR can detect ground movement as small as a centimeter from orbit, letting scientists track earthquakes, glaciers, and crop growth on almost the entire planet every twelve days." },
  { q: "Which NASA helicopter became the first aircraft to achieve powered, controlled flight on another planet?", o: ["Dragonfly", "Ingenuity", "Volatiles Investigating Polar Exploration Rover", "Mars Helicopter Scout"], a: "Ingenuity", d: "Earthbound", c: "NASA", insight: "Mars' atmosphere is only about 1% as dense as Earth's, so Ingenuity's rotors had to spin roughly five times faster than a comparable helicopter would need to just to get off the ground." },

  // Orbit
  { q: "Who commanded the Artemis II mission that flew around the Moon in April 2026?", o: ["Victor Glover", "Reid Wiseman", "Christina Koch", "Jeremy Hansen"], a: "Reid Wiseman", d: "Orbit", c: "NASA", insight: "Wiseman logged nearly six months aboard the ISS in 2014 and later led NASA's Astronaut Office before being named commander of the first crewed mission beyond low Earth orbit in over 50 years." },
  { q: "Artemis II set a new human distance-from-Earth record. Approximately how far from Earth did the crew travel at their farthest point?", o: ["150,000 miles", "252,000 miles", "400,000 miles", "500,000 miles"], a: "252,000 miles", d: "Orbit", c: "NASA", insight: "That distance came from looping around the far side of the Moon and using its gravity to fling Orion back toward Earth — the same free-return trajectory Apollo 13 used to get its crew home safely." },
  { q: "Which Canadian astronaut flew on Artemis II, becoming the first non-American to travel to the Moon?", o: ["David Saint-Jacques", "Jeremy Hansen", "Chris Hadfield", "Julie Payette"], a: "Jeremy Hansen", d: "Orbit", c: "NASA", insight: "Canada earned the seat by contributing Canadarm3, a robotic arm system, to NASA's Gateway lunar station — hardware traded for a flight opportunity." },
  { q: "What major change did NASA announce in early 2026 regarding future SLS configurations after Artemis II?", o: ["Switch entirely to Falcon Heavy", "Standardize on a near Block 1 configuration instead of upgrading to Block 1B/2", "Cancel SLS after Artemis III", "Add a nuclear upper stage"], a: "Standardize on a near Block 1 configuration instead of upgrading to Block 1B/2", d: "Orbit", c: "NASA", insight: "The heavier Block 1B and Block 2 upgrades depend on a larger upper stage that wasn't ready in time, so NASA opted to keep flying the proven configuration rather than delay the program further." },
  { q: "Artemis III is planned as what type of mission in 2027?", o: ["First human lunar landing since Apollo", "Low Earth orbit demonstration of rendezvous and docking with commercial landers", "Crewed Mars flyby", "Gateway assembly mission"], a: "Low Earth orbit demonstration of rendezvous and docking with commercial landers", d: "Orbit", c: "NASA", insight: "Proving astronauts can safely rendezvous and dock with a commercial lander in Earth orbit first means catching any problems close to home, rather than for the first time out at the Moon." },
  { q: "Which NASA mission launched in October 2024 and is currently en route to study Jupiter's moon Europa?", o: ["Juno", "Europa Clipper", "JUICE", "Lucy"], a: "Europa Clipper", d: "Orbit", c: "NASA", insight: "Clipper is the largest spacecraft NASA has ever built for a planetary mission — its solar arrays span more than 100 feet, because sunlight at Jupiter is about 25 times weaker than at Earth." },
  { q: "When is Europa Clipper scheduled to perform its Earth gravity assist flyby?", o: ["March 2025", "December 2026", "April 2028", "October 2029"], a: "December 2026", d: "Orbit", c: "NASA", insight: "Rather than carry enough fuel to fly straight to Jupiter, Clipper swings back past Earth to steal a bit of the planet's orbital momentum — the same trick gravity-assist missions have used since Voyager." },
  { q: "What is the primary science goal of the Europa Clipper mission?", o: ["Land on Europa and drill into the ice", "Assess the habitability of Europa's subsurface ocean", "Search for active volcanoes on Io", "Map Jupiter's magnetic field in detail"], a: "Assess the habitability of Europa's subsurface ocean", d: "Orbit", c: "NASA", insight: "Clipper won't search for life directly — its job is to find out whether Europa's ocean has the chemistry and energy to support it, before any future mission tries to look." },
  { q: "NASA's Nancy Grace Roman Space Telescope is scheduled to launch in which month of 2026?", o: ["March", "June", "August", "November"], a: "August", d: "Orbit", c: "NASA", insight: "Roman is built around mirror hardware originally made for a spy satellite and later donated to NASA, paired with a camera giving it a field of view about 100 times larger than Hubble's." },
  { q: "What is the name of the twin NASA spacecraft launched in November 2025 on New Glenn to study how the solar wind strips Mars' atmosphere?", o: ["MAVEN", "ESCAPADE", "Mars Odyssey", "Hope"], a: "ESCAPADE", d: "Orbit", c: "NASA", insight: "Flying two identical spacecraft instead of one lets ESCAPADE measure Mars' magnetic environment from two points at once, showing how the solar wind strips the atmosphere in something closer to 3D." },
  { q: "Which astronaut became the first woman to travel to the Moon on Artemis II?", o: ["Jessica Meir", "Christina Koch", "Anne McClain", "Kayla Barron"], a: "Christina Koch", d: "Orbit", c: "NASA", insight: "Koch already held the record for the longest single spaceflight by a woman — 328 days on the ISS — before being named to the Artemis II crew." },
  { q: "What is the name of NASA's planned lunar surface outpost effort that shifted focus away from the orbital Gateway in 2026?", o: ["Lunar Gateway", "Moon Base", "Artemis Camp", "South Pole Station"], a: "Moon Base", d: "Orbit", c: "NASA", insight: "It's the same lesson early Antarctic expeditions learned the hard way: a base on the ground can support work year-round, while a station in orbit only ever visits." },

  // Martian
  { q: "Who is the commander of the Artemis III crew announced in 2026?", o: ["Reid Wiseman", "Randy Bresnik", "Victor Glover", "Frank Rubio"], a: "Randy Bresnik", d: "Martian", c: "NASA", insight: "Bresnik has already flown the Space Shuttle and commanded a long-duration ISS expedition — Artemis III adds a third, very different way of reaching space to his career." },
  { q: "Which European Space Agency astronaut is scheduled to fly as pilot on Artemis III?", o: ["Samantha Cristoforetti", "Luca Parmitano", "Thomas Pesquet", "Alexander Gerst"], a: "Luca Parmitano", d: "Martian", c: "NASA", insight: "Parmitano is a veteran of two long-duration ISS missions, and once had to cut a spacewalk short after water began leaking into his helmet — an incident that reshaped NASA's spacewalk safety procedures." },
  { q: "When did NASA join the Orion crew and service modules together for the Artemis III mission?", o: ["March 2026", "May 2026", "July 2026", "September 2026"], a: "July 2026", d: "Martian", c: "NASA", insight: "The service module is built by the European Space Agency and supplies Orion's propulsion, power, and air and water — NASA's crew capsule literally can't fly without a European-built half." },
  { q: "Approximately how many close flybys of Europa does Europa Clipper plan to perform during its prime mission?", o: ["12", "25", "49", "80"], a: "49", d: "Martian", c: "NASA", insight: "Clipper loops around Jupiter and ducks in and out of its radiation belts on each flyby rather than settling into orbit around Europa — a full-time orbit there would fry its electronics far faster." },
  { q: "In what year is Europa Clipper currently scheduled to arrive at the Jupiter system?", o: ["2028", "2030", "2032", "2035"], a: "2030", d: "Martian", c: "NASA", insight: "The six-year cruise is a fuel-saving trade-off — Clipper's path uses gravity assists from Mars and Earth instead of a more direct route that would need far more propellant to fly." },
  { q: "What is the approximate total distance Europa Clipper will travel from Earth to Jupiter?", o: ["500 million miles", "1.0 billion miles", "1.8 billion miles", "3.2 billion miles"], a: "1.8 billion miles", d: "Martian", c: "NASA", insight: "That's roughly the distance of nineteen round trips to the Moon, all to reach a moon that from Earth looks like a faint dot next to Jupiter." },
  { q: "NASA's Roman Space Telescope will primarily operate at which special location in space?", o: ["Low Earth orbit", "Geostationary orbit", "Earth-Sun L2 Lagrange point", "Lunar orbit"], a: "Earth-Sun L2 Lagrange point", d: "Martian", c: "NASA", insight: "L2 is a gravitational balance point where a spacecraft can stay aligned with Earth's shadow, keeping the Sun, Earth, and Moon all blocked behind a single sunshield — the same spot Webb uses." },
  { q: "What is the diameter of the primary mirror on the Nancy Grace Roman Space Telescope?", o: ["1.5 meters", "2.4 meters", "3.5 meters", "6.5 meters"], a: "2.4 meters", d: "Martian", c: "NASA", insight: "That's the same mirror size as Hubble, but Roman pairs it with a much wider-field camera — able to survey in weeks the kind of sky area that would take Hubble years to cover." },
  { q: "Which two companies are currently developing Human Landing Systems for NASA's Artemis program?", o: ["Blue Origin and Rocket Lab", "SpaceX and Blue Origin", "Lockheed Martin and Northrop Grumman", "Boeing and Sierra Space"], a: "SpaceX and Blue Origin", d: "Martian", c: "NASA", insight: "NASA is funding two competing lunar landers rather than one — a hedge after Commercial Crew's reliance on a single backup provider left the program with little room when that provider's schedule slipped for years." },
  { q: "Artemis II's Orion spacecraft was given what name by its crew?", o: ["Endeavour", "Integrity", "Discovery", "Columbia"], a: "Integrity", d: "Martian", c: "NASA", insight: "Naming the capsule is an Apollo-era tradition NASA revived for Artemis — Apollo 11's command module was Columbia, and its lunar lander was Eagle." },

  // ========== Deep Space ==========

  // Earthbound
  { q: "What is the primary long-term goal of making life multi-planetary?", o: ["Mining asteroids for rare metals", "Ensuring the long-term survival of humanity", "Building faster internet satellites", "Studying cosmic rays"], a: "Ensuring the long-term survival of humanity", d: "Earthbound", c: "Deep Space" },
  { q: "Which planet is currently the main focus for future human exploration beyond the Moon?", o: ["Venus", "Mars", "Jupiter", "Saturn"], a: "Mars", d: "Earthbound", c: "Deep Space" },
  { q: "What does ISRU stand for in the context of space exploration?", o: ["International Space Research Unit", "In-Situ Resource Utilization", "Interplanetary Supply and Resupply Unit", "Integrated Spacecraft Refueling Utility"], a: "In-Situ Resource Utilization", d: "Earthbound", c: "Deep Space" },
  { q: "Which moon of Jupiter is widely considered one of the best places in the solar system to search for life?", o: ["Io", "Ganymede", "Europa", "Callisto"], a: "Europa", d: "Earthbound", c: "Deep Space" },
  { q: "What type of propulsion uses nuclear reactions to heat propellant for higher efficiency than chemical rockets?", o: ["Ion propulsion", "Nuclear Thermal Propulsion", "Solar sails", "Hall-effect thrusters"], a: "Nuclear Thermal Propulsion", d: "Earthbound", c: "Deep Space" },
  { q: "What is the name of the concept for a permanent human outpost at the lunar south pole?", o: ["Lunar Gateway", "Moon Base", "Artemis Village", "Shackleton Station"], a: "Moon Base", d: "Earthbound", c: "Deep Space" },
  { q: "Which NASA mission successfully returned samples from the asteroid Bennu?", o: ["Hayabusa2", "OSIRIS-REx", "Dawn", "Lucy"], a: "OSIRIS-REx", d: "Earthbound", c: "Deep Space" },
  { q: "What is the main advantage of launching spacecraft from the Moon versus Earth?", o: ["Stronger gravity assists", "Much lower escape velocity and no atmosphere", "Closer to the Sun", "Easier communication"], a: "Much lower escape velocity and no atmosphere", d: "Earthbound", c: "Deep Space" },
  { q: "Which gas is a primary target for extraction from the lunar south pole for future propellant and life support?", o: ["Nitrogen", "Water ice (for hydrogen and oxygen)", "Methane", "Carbon dioxide"], a: "Water ice (for hydrogen and oxygen)", d: "Earthbound", c: "Deep Space" },
  { q: "What is the name of the planned NASA mission that will send a rotorcraft to explore Titan?", o: ["Dragonfly", "Ingenuity", "Perseverance", "Curiosity"], a: "Dragonfly", d: "Earthbound", c: "Deep Space" },

  // Orbit
  { q: "What is the approximate one-way light-time communication delay between Earth and Mars at average distances?", o: ["1–2 minutes", "4–24 minutes", "1–2 hours", "1 day"], a: "4–24 minutes", d: "Orbit", c: "Deep Space" },
  { q: "Why is the lunar south pole considered the preferred location for a long-term Moon base?", o: ["It is warmer year-round", "Near-permanent sunlight on peaks and water ice in permanently shadowed craters", "It has the strongest magnetic field", "It is closest to Earth"], a: "Near-permanent sunlight on peaks and water ice in permanently shadowed craters", d: "Orbit", c: "Deep Space" },
  { q: "What is the primary purpose of a Mars Sample Return campaign?", o: ["To test human landing systems", "To bring carefully selected Martian rock and soil samples back to Earth for detailed laboratory analysis", "To establish a fuel depot", "To search for current liquid water on the surface"], a: "To bring carefully selected Martian rock and soil samples back to Earth for detailed laboratory analysis", d: "Orbit", c: "Deep Space" },
  { q: "Which propulsion technology is considered one of the most promising for crewed Mars missions due to its high specific impulse?", o: ["Solid rocket motors", "Nuclear Thermal Propulsion or advanced electric propulsion", "Cold gas thrusters", "Chemical bipropellant only"], a: "Nuclear Thermal Propulsion or advanced electric propulsion", d: "Orbit", c: "Deep Space" },
  { q: "What is a major radiation challenge for deep-space human missions beyond low Earth orbit?", o: ["Only ultraviolet light", "Galactic cosmic rays and solar particle events", "Only Van Allen belt radiation", "Infrared heating"], a: "Galactic cosmic rays and solar particle events", d: "Orbit", c: "Deep Space" },
  { q: "Which moon of Saturn has a thick atmosphere and lakes of liquid hydrocarbons, making it a high-priority target for life detection?", o: ["Enceladus", "Titan", "Mimas", "Rhea"], a: "Titan", d: "Orbit", c: "Deep Space" },
  { q: "What is the main scientific reason Europa is considered potentially habitable?", o: ["It has active volcanoes", "Strong evidence of a global subsurface saltwater ocean in contact with a rocky seafloor", "It has a thick oxygen atmosphere", "It is geologically dead and stable"], a: "Strong evidence of a global subsurface saltwater ocean in contact with a rocky seafloor", d: "Orbit", c: "Deep Space" },
  { q: "What does the term \"delta-v\" represent in deep-space mission design?", o: ["The total change in velocity a spacecraft must achieve", "The diameter of the launch vehicle", "The daily data volume", "The time between course corrections"], a: "The total change in velocity a spacecraft must achieve", d: "Orbit", c: "Deep Space" },
  { q: "Which future telescope concept is designed to directly image Earth-like exoplanets around nearby stars?", o: ["James Webb Space Telescope", "Nancy Grace Roman Space Telescope (with coronagraph)", "Hubble Space Telescope", "Chandra X-ray Observatory"], a: "Nancy Grace Roman Space Telescope (with coronagraph)", d: "Orbit", c: "Deep Space" },
  { q: "What is one of the biggest engineering challenges of landing heavy payloads on Mars?", o: ["Too much atmospheric drag", "The thin atmosphere provides limited aerodynamic braking for large vehicles", "Excessive magnetic fields", "Constant dust storms that never clear"], a: "The thin atmosphere provides limited aerodynamic braking for large vehicles", d: "Orbit", c: "Deep Space" },

  // Martian
  { q: "Approximately how long would a one-way crewed trip to Mars take using current chemical propulsion and optimal trajectories?", o: ["1–2 months", "6–9 months", "18–24 months", "3–4 years"], a: "6–9 months", d: "Martian", c: "Deep Space" },
  { q: "What is the primary goal of NASA's planned Dragonfly mission to Titan?", o: ["Land and return samples to Earth", "Fly a rotorcraft to multiple sites and study prebiotic chemistry and habitability", "Establish a permanent base", "Map the entire surface with radar only"], a: "Fly a rotorcraft to multiple sites and study prebiotic chemistry and habitability", d: "Martian", c: "Deep Space" },
  { q: "Which propulsion concept uses a nuclear reactor to generate electricity that then powers ion or Hall thrusters?", o: ["Nuclear Thermal Propulsion", "Nuclear Electric Propulsion", "Chemical bipropellant", "Solar sail"], a: "Nuclear Electric Propulsion", d: "Martian", c: "Deep Space" },
  { q: "What is the approximate thickness of Europa's ice shell according to current best estimates?", o: ["A few meters", "Several to tens of kilometers", "Hundreds of kilometers", "Completely solid with no ocean"], a: "Several to tens of kilometers", d: "Martian", c: "Deep Space" },
  { q: "Why are permanently shadowed regions at the lunar poles scientifically and operationally important?", o: ["They are the warmest places on the Moon", "They can trap water ice and other volatiles for billions of years", "They have the strongest sunlight", "They are free of radiation"], a: "They can trap water ice and other volatiles for billions of years", d: "Martian", c: "Deep Space" },
  { q: "What is a key advantage of using nuclear thermal propulsion for crewed Mars missions compared to chemical rockets?", o: ["It requires no propellant", "Higher specific impulse allowing shorter trip times and reduced radiation exposure", "It works only in atmosphere", "It is cheaper to develop"], a: "Higher specific impulse allowing shorter trip times and reduced radiation exposure", d: "Martian", c: "Deep Space" },
  { q: "Which NASA mission concept aims to return carefully selected samples from Mars that Perseverance has already collected and cached?", o: ["Mars Sample Return", "Mars 2020", "Insight", "Phoenix"], a: "Mars Sample Return", d: "Martian", c: "Deep Space" },
  { q: "What is the main reason a crewed Mars mission would likely involve a long surface stay (months to over a year)?", o: ["To wait for better weather", "Planetary alignment and the energy required for the return trajectory", "To grow enough food", "Because the spacecraft needs repairs"], a: "Planetary alignment and the energy required for the return trajectory", d: "Martian", c: "Deep Space" },
  { q: "Which icy moon of Saturn is known for active water-ice geysers erupting from its south polar region?", o: ["Titan", "Enceladus", "Mimas", "Iapetus"], a: "Enceladus", d: "Martian", c: "Deep Space" },
  { q: "What is the approximate diameter of Europa?", o: ["About the size of Earth's Moon", "Roughly half the size of Earth's Moon", "Larger than Mars", "Similar to Mercury"], a: "About the size of Earth's Moon", d: "Martian", c: "Deep Space" },

  // ========== Commercial Space ==========

  // Earthbound
  { q: "Which company developed the New Glenn rocket?", o: ["SpaceX", "Blue Origin", "Rocket Lab", "Relativity Space"], a: "Blue Origin", d: "Earthbound", c: "Commercial Space" },
  { q: "What is the name of Blue Origin's lunar lander being developed for NASA's Artemis program?", o: ["Starship HLS", "Blue Moon", "Nova-C", "Griffin"], a: "Blue Moon", d: "Earthbound", c: "Commercial Space" },
  { q: "Which company operates the Electron small-lift rocket?", o: ["Rocket Lab", "Firefly Aerospace", "Astra", "Virgin Orbit"], a: "Rocket Lab", d: "Earthbound", c: "Commercial Space" },
  { q: "What is the name of Rocket Lab's medium-lift rocket currently in development?", o: ["Electron", "Neutron", "Photon", "HASTE"], a: "Neutron", d: "Earthbound", c: "Commercial Space" },
  { q: "Which commercial company successfully landed multiple times on the Moon under NASA's CLPS program by mid-2026?", o: ["Only SpaceX", "Intuitive Machines and Firefly Aerospace", "Blue Origin only", "Relativity Space"], a: "Intuitive Machines and Firefly Aerospace", d: "Earthbound", c: "Commercial Space" },
  { q: "What is the name of Firefly Aerospace's successful lunar lander mission that touched down in 2025?", o: ["IM-1", "Blue Ghost Mission 1", "Peregrine", "Nova-C"], a: "Blue Ghost Mission 1", d: "Earthbound", c: "Commercial Space" },
  { q: "Which company is building the Starlink satellite constellation?", o: ["Amazon", "SpaceX", "OneWeb", "Telesat"], a: "SpaceX", d: "Earthbound", c: "Commercial Space" },
  { q: "What is Amazon's satellite internet constellation project called?", o: ["Starlink", "Project Kuiper", "OneWeb", "Iridium"], a: "Project Kuiper", d: "Earthbound", c: "Commercial Space" },
  { q: "Which commercial company is developing a private space station called Axiom Station?", o: ["Blue Origin", "Axiom Space", "Sierra Space", "Nanoracks"], a: "Axiom Space", d: "Earthbound", c: "Commercial Space" },
  { q: "What is the name of the reusable first stage catch system SpaceX uses with the Super Heavy booster?", o: ["Octagrabber", "Mechazilla", "Chopsticks", "Tower Arms"], a: "Mechazilla", d: "Earthbound", c: "Commercial Space" },

  // Orbit
  { q: "In May 2026, Blue Origin experienced a major anomaly with which rocket during testing?", o: ["New Shepard", "New Glenn", "Blue Moon", "BE-4 engine only"], a: "New Glenn", d: "Orbit", c: "Commercial Space" },
  { q: "Which company launched NASA's ESCAPADE mission to Mars in November 2025?", o: ["SpaceX", "Blue Origin", "ULA", "Rocket Lab"], a: "Blue Origin", d: "Orbit", c: "Commercial Space" },
  { q: "What is the primary goal of Rocket Lab's Neutron rocket?", o: ["Only small satellite launches", "Medium-lift reusable launches and potential human spaceflight capability", "Heavy-lift only", "Lunar landings exclusively"], a: "Medium-lift reusable launches and potential human spaceflight capability", d: "Orbit", c: "Commercial Space" },
  { q: "Which commercial lunar lander tipped over after landing but still returned significant science data in 2025?", o: ["Blue Ghost", "IM-2 (Intuitive Machines)", "Peregrine", "XL-1"], a: "IM-2 (Intuitive Machines)", d: "Orbit", c: "Commercial Space" },
  { q: "What is the name of Sierra Space's inflatable space station module technology?", o: ["BEAM", "LIFE", "Haven", "Orbital Reef"], a: "LIFE", d: "Orbit", c: "Commercial Space" },
  { q: "Which two companies are partnering on the Orbital Reef commercial space station concept?", o: ["SpaceX and Axiom", "Blue Origin and Sierra Space", "Rocket Lab and Lockheed", "Boeing and Northrop Grumman"], a: "Blue Origin and Sierra Space", d: "Orbit", c: "Commercial Space" },
  { q: "What engine powers the first stage of Blue Origin's New Glenn rocket?", o: ["Raptor", "BE-4", "RS-25", "Merlin"], a: "BE-4", d: "Orbit", c: "Commercial Space" },
  { q: "Which company is developing the Terran R fully reusable rocket using 3D-printed engines?", o: ["Relativity Space", "Stoke Space", "Firefly", "Astra"], a: "Relativity Space", d: "Orbit", c: "Commercial Space" },
  { q: "What is the name of Stoke Space's novel reusable upper stage approach that uses a regeneratively cooled heat shield?", o: ["Nova", "Nova 2", "Fully reusable second stage with active cooling", "Photon"], a: "Fully reusable second stage with active cooling", d: "Orbit", c: "Commercial Space" },
  { q: "Which commercial company completed the first soft landing of a CLPS mission on the Moon in early 2024?", o: ["Firefly", "Intuitive Machines (IM-1)", "Astrobotic", "ispace"], a: "Intuitive Machines (IM-1)", d: "Orbit", c: "Commercial Space" },

  // Martian
  { q: "As of mid-2026, what was the status of Blue Origin's New Glenn after its May test anomaly?", o: ["Permanently retired", "Repairs underway with goal to resume flights by end of 2026", "Converted to New Shepard", "Sold to ULA"], a: "Repairs underway with goal to resume flights by end of 2026", d: "Martian", c: "Commercial Space" },
  { q: "Which commercial company is developing a large lunar lander called Griffin for NASA's VIPER rover (later cancelled/reworked)?", o: ["Astrobotic", "Intuitive Machines", "Firefly", "Blue Origin"], a: "Astrobotic", d: "Martian", c: "Commercial Space" },
  { q: "What is the approximate payload capacity of Rocket Lab's Neutron rocket to low Earth orbit in its reusable configuration?", o: ["300 kg", "1,500 kg", "8,000–15,000 kg class", "50,000 kg"], a: "8,000–15,000 kg class", d: "Martian", c: "Commercial Space" },
  { q: "Which company is building the Haven-1 private space station module planned as an early commercial destination?", o: ["Axiom Space", "Vast", "Sierra Space", "Blue Origin"], a: "Vast", d: "Martian", c: "Commercial Space" },
  { q: "What is the name of the BE-4 engine's fuel combination?", o: ["LOX/RP-1", "LOX/Liquid Methane (LNG)", "LOX/Liquid Hydrogen", "Hypergolic"], a: "LOX/Liquid Methane (LNG)", d: "Martian", c: "Commercial Space" },

  // ========== Planetary Science ==========

  // Earthbound
  { q: "Which planet has the largest volcano in the solar system, Olympus Mons?", o: ["Earth", "Venus", "Mars", "Mercury"], a: "Mars", d: "Earthbound", c: "Planetary Science" },
  { q: "What is the name of the largest moon of Saturn?", o: ["Europa", "Titan", "Ganymede", "Callisto"], a: "Titan", d: "Earthbound", c: "Planetary Science" },
  { q: "Which planet is known for its extreme greenhouse effect and surface temperatures hot enough to melt lead?", o: ["Mercury", "Venus", "Mars", "Jupiter"], a: "Venus", d: "Earthbound", c: "Planetary Science" },
  { q: "What is the primary composition of the ice giant planets Uranus and Neptune's atmospheres?", o: ["Mostly hydrogen and helium with methane", "Mostly nitrogen and oxygen", "Mostly carbon dioxide", "Mostly sulfur compounds"], a: "Mostly hydrogen and helium with methane", d: "Earthbound", c: "Planetary Science" },
  { q: "Which spacecraft returned samples from the asteroid Bennu to Earth in 2023?", o: ["Hayabusa2", "OSIRIS-REx", "Dawn", "NEAR Shoemaker"], a: "OSIRIS-REx", d: "Earthbound", c: "Planetary Science" },
  { q: "What is the name of Jupiter's largest moon?", o: ["Europa", "Io", "Ganymede", "Callisto"], a: "Ganymede", d: "Earthbound", c: "Planetary Science" },
  { q: "Which planet has a day longer than its year?", o: ["Mercury", "Venus", "Mars", "Neptune"], a: "Venus", d: "Earthbound", c: "Planetary Science" },
  { q: "What causes the intense radiation environment around Jupiter?", o: ["Its weak magnetic field", "Its powerful magnetic field trapping charged particles", "Constant volcanic eruptions on Io only", "Proximity to the Sun"], a: "Its powerful magnetic field trapping charged particles", d: "Earthbound", c: "Planetary Science" },
  { q: "Which moon of Saturn is famous for its bright, icy surface and active water-ice geysers?", o: ["Titan", "Enceladus", "Mimas", "Rhea"], a: "Enceladus", d: "Earthbound", c: "Planetary Science" },
  { q: "What is the main reason Mars appears red?", o: ["Nitrogen atmosphere", "Iron oxide (rust) on its surface", "Sulfur deposits", "Methane clouds"], a: "Iron oxide (rust) on its surface", d: "Earthbound", c: "Planetary Science" },

  // Orbit
  { q: "Which NASA mission is currently studying the metal-rich asteroid Psyche?", o: ["Lucy", "Psyche", "Dawn", "OSIRIS-APEX"], a: "Psyche", d: "Orbit", c: "Planetary Science" },
  { q: "What is the primary goal of ESA's Hera mission?", o: ["Land on Mars", "Study the binary asteroid system impacted by NASA's DART mission", "Orbit Europa", "Return samples from Venus"], a: "Study the binary asteroid system impacted by NASA's DART mission", d: "Orbit", c: "Planetary Science" },
  { q: "Which spacecraft discovered that Enceladus has a global subsurface ocean?", o: ["Voyager 1", "Cassini", "Galileo", "New Horizons"], a: "Cassini", d: "Orbit", c: "Planetary Science" },
  { q: "What is the name of the NASA mission planned to send a rotorcraft to multiple sites on Titan?", o: ["Ingenuity", "Dragonfly", "Mars Helicopter", "Volatiles Investigating Polar Exploration Rover"], a: "Dragonfly", d: "Orbit", c: "Planetary Science" },
  { q: "Which planet's atmosphere is primarily responsible for the runaway greenhouse effect we observe today?", o: ["Mars", "Venus", "Earth", "Titan"], a: "Venus", d: "Orbit", c: "Planetary Science" },
  { q: "What is the approximate age of the solar system based on radiometric dating of meteorites?", o: ["2.5 billion years", "4.6 billion years", "6.0 billion years", "10 billion years"], a: "4.6 billion years", d: "Orbit", c: "Planetary Science" },
  { q: "Which moon is the most volcanically active body in the solar system?", o: ["Europa", "Io", "Enceladus", "Triton"], a: "Io", d: "Orbit", c: "Planetary Science" },
  { q: "What is the main scientific interest in the dwarf planet Ceres?", o: ["It has active volcanoes of molten rock", "Evidence of past and possibly present water activity and organic compounds", "It is mostly metallic", "It has a thick nitrogen atmosphere"], a: "Evidence of past and possibly present water activity and organic compounds", d: "Orbit", c: "Planetary Science" },
  { q: "Which mission first provided detailed images and data of Pluto and its moons?", o: ["Voyager 2", "New Horizons", "Cassini", "Pioneer 10"], a: "New Horizons", d: "Orbit", c: "Planetary Science" },
  { q: "What is the name of the large impact basin on Mars that is one of the largest in the solar system?", o: ["Hellas Basin", "Caloris Basin", "South Pole-Aitken Basin", "Orientale Basin"], a: "Hellas Basin", d: "Orbit", c: "Planetary Science" },

  // Martian
  { q: "Which two NASA missions are planned to study Venus in the 2030s, focusing on its atmosphere and surface?", o: ["DAVINCI and VERITAS", "Europa Clipper and JUICE", "Dragonfly and Psyche", "Lucy and Hera"], a: "DAVINCI and VERITAS", d: "Martian", c: "Planetary Science" },
  { q: "What is the estimated depth of the global ocean believed to exist beneath Europa's ice shell?", o: ["A few hundred meters", "Tens to over 100 kilometers", "Only a thin layer of meltwater", "No liquid water exists"], a: "Tens to over 100 kilometers", d: "Martian", c: "Planetary Science" },
  { q: "Which asteroid did NASA's Lucy spacecraft fly by in 2025, providing the first close-up images of a main-belt asteroid of its type?", o: ["Bennu", "Donaldjohanson", "Psyche", "Didymos"], a: "Donaldjohanson", d: "Martian", c: "Planetary Science" },
  { q: "What is the primary scientific goal of studying Titan's organic chemistry?", o: ["To find current life", "To understand prebiotic chemistry in a nitrogen-rich, organic-rich environment similar to early Earth", "To mine hydrocarbons", "To search for metallic core exposure"], a: "To understand prebiotic chemistry in a nitrogen-rich, organic-rich environment similar to early Earth", d: "Martian", c: "Planetary Science" },
  { q: "Which planetary body has the tallest known cliffs or scarps in the solar system, created by global contraction?", o: ["Mars", "Mercury", "Moon", "Europa"], a: "Mercury", d: "Martian", c: "Planetary Science" },
  { q: "What is the name of the large dark region on Pluto that is a nitrogen ice plain?", o: ["Tombaugh Regio", "Sputnik Planitia", "Cthulhu Macula", "Wright Mons"], a: "Sputnik Planitia", d: "Martian", c: "Planetary Science" },
  { q: "Which moon of Neptune is unique for orbiting in the opposite direction of the planet's rotation and showing signs of past geologic activity?", o: ["Proteus", "Triton", "Nereid", "Larissa"], a: "Triton", d: "Martian", c: "Planetary Science" },
  { q: "What is the main evidence that Mars once had a thicker atmosphere and liquid water on its surface?", o: ["Current active rivers", "Ancient river valleys, lake beds, and mineral deposits formed in water", "Only polar ice caps", "Frequent rainfall observed today"], a: "Ancient river valleys, lake beds, and mineral deposits formed in water", d: "Martian", c: "Planetary Science" },
  { q: "Which spacecraft is currently the longest-operating planetary orbiter at Mars?", o: ["Mars Reconnaissance Orbiter", "Mars Odyssey", "MAVEN", "Mars Express"], a: "Mars Odyssey", d: "Martian", c: "Planetary Science" },
  { q: "What is the approximate surface pressure of Venus compared to Earth?", o: ["About the same", "Roughly 90 times higher", "10 times lower", "Only slightly higher"], a: "Roughly 90 times higher", d: "Martian", c: "Planetary Science" },

  // ========== ESA ==========

  // Earthbound
  { q: "What does ESA stand for?", o: ["European Space Agency", "European Science Association", "Earth Space Alliance", "Euro Satellite Agency"], a: "European Space Agency", d: "Earthbound", c: "ESA" },
  { q: "Which rocket is ESA's current heavy-lift launcher?", o: ["Ariane 5", "Ariane 6", "Vega C", "Soyuz"], a: "Ariane 6", d: "Earthbound", c: "ESA" },
  { q: "What is the name of ESA's major mission to study Jupiter and its icy moons?", o: ["Juno", "JUICE", "Europa Clipper", "Galileo"], a: "JUICE", d: "Earthbound", c: "ESA" },
  { q: "Which country hosts Europe's Spaceport, from which Ariane rockets launch?", o: ["France (mainland)", "French Guiana", "Germany", "Italy"], a: "French Guiana", d: "Earthbound", c: "ESA" },
  { q: "What is the name of the European-built module that provides power and propulsion for NASA's Orion spacecraft?", o: ["European Service Module", "Columbus Module", "ATV", "Automated Transfer Vehicle"], a: "European Service Module", d: "Earthbound", c: "ESA" },
  { q: "Which ESA mission is mapping the dark universe and studying dark energy and dark matter?", o: ["Euclid", "Planck", "Herschel", "Gaia"], a: "Euclid", d: "Earthbound", c: "ESA" },
  { q: "What is the name of ESA's small-lift rocket that complements Ariane 6?", o: ["Vega C", "Soyuz", "Falcon 9", "Electron"], a: "Vega C", d: "Earthbound", c: "ESA" },
  { q: "Which ESA astronaut flew as a mission specialist on Artemis II?", o: ["Luca Parmitano", "Jeremy Hansen", "Thomas Pesquet", "Samantha Cristoforetti"], a: "Jeremy Hansen", d: "Earthbound", c: "ESA" },
  { q: "What is the primary science focus of the JUICE mission?", o: ["Landing on Europa", "Studying Jupiter and its ocean-bearing moons Ganymede, Europa, and Callisto", "Mapping Venus", "Returning samples from Mars"], a: "Studying Jupiter and its ocean-bearing moons Ganymede, Europa, and Callisto", d: "Earthbound", c: "ESA" },
  { q: "Which ESA mission is currently orbiting the Sun and studying its poles and solar wind?", o: ["Solar Orbiter", "Parker Solar Probe", "SOHO", "STEREO"], a: "Solar Orbiter", d: "Earthbound", c: "ESA" },

  // Orbit
  { q: "When was ESA's JUICE spacecraft launched?", o: ["2021", "April 2023", "2024", "2025"], a: "April 2023", d: "Orbit", c: "ESA" },
  { q: "In what year is JUICE currently scheduled to arrive at Jupiter?", o: ["2028", "2031", "2033", "2035"], a: "2031", d: "Orbit", c: "ESA" },
  { q: "Which moon will JUICE eventually orbit, making it the first spacecraft to orbit a moon other than Earth's?", o: ["Europa", "Callisto", "Ganymede", "Io"], a: "Ganymede", d: "Orbit", c: "ESA" },
  { q: "What major gravity-assist flyby is JUICE scheduled to perform in September 2026?", o: ["Venus", "Earth", "Mars", "Moon only"], a: "Earth", d: "Orbit", c: "ESA" },
  { q: "Which ESA mission made a close observation of the interstellar comet 3I/ATLAS in late 2025?", o: ["Euclid", "JUICE", "Solar Orbiter", "BepiColombo"], a: "JUICE", d: "Orbit", c: "ESA" },
  { q: "What is the name of the ESA-led mission currently en route to Mercury with JAXA?", o: ["BepiColombo", "MESSENGER", "Parker", "Solar Orbiter"], a: "BepiColombo", d: "Orbit", c: "ESA" },
  { q: "Which European astronaut is scheduled to fly as pilot on Artemis III?", o: ["Thomas Pesquet", "Luca Parmitano", "Alexander Gerst", "Samantha Cristoforetti"], a: "Luca Parmitano", d: "Orbit", c: "ESA" },
  { q: "Ariane 6 successfully launched multiple missions for which major commercial satellite constellation in 2026?", o: ["Starlink", "Amazon Leo (formerly Project Kuiper)", "OneWeb", "Iridium"], a: "Amazon Leo (formerly Project Kuiper)", d: "Orbit", c: "ESA" },
  { q: "What is the approximate size of JUICE's solar arrays, among the largest ever flown on an interplanetary mission?", o: ["25 m²", "50 m²", "85 m²", "120 m²"], a: "85 m²", d: "Orbit", c: "ESA" },
  { q: "Which ESA cosmology mission is designed to create a 3D map of the universe to better understand dark energy?", o: ["Gaia", "Euclid", "Planck", "Herschel"], a: "Euclid", d: "Orbit", c: "ESA" },

  // Martian
  { q: "How many major gravity assists will JUICE perform before arriving at Jupiter?", o: ["Two", "Four (including Moon-Earth and Venus)", "Six", "Only one"], a: "Four (including Moon-Earth and Venus)", d: "Martian", c: "ESA" },
  { q: "What is the planned duration of JUICE's science phase in the Jupiter system?", o: ["About 1 year", "At least 3.5 years", "10 years", "Only 6 months"], a: "At least 3.5 years", d: "Martian", c: "ESA" },
  { q: "Which instrument suite on JUICE is specifically designed for radio science and precise tracking of the spacecraft's motion?", o: ["JANUS", "PRIDE", "GALA", "RIME"], a: "PRIDE", d: "Martian", c: "ESA" },
  { q: "In 2026, Ariane 6 began flying the more powerful configuration with four solid boosters known as what?", o: ["Ariane 62", "Ariane 64", "Ariane 6 Heavy", "Ariane Next"], a: "Ariane 64", d: "Martian", c: "ESA" },
  { q: "What is the name of the ESA contribution to the International Space Station that serves as a laboratory module?", o: ["Destiny", "Columbus", "Kibo", "Harmony"], a: "Columbus", d: "Martian", c: "ESA" },
  { q: "Which ESA mission is planned to launch in the late 2020s to study the atmosphere and surface of Venus?", o: ["EnVision", "DAVINCI", "VERITAS", "Akatsuki"], a: "EnVision", d: "Martian", c: "ESA" },
  { q: "JUICE will perform only a limited number of flybys of Europa due to what major environmental concern?", o: ["Lack of scientific interest", "Extremely high radiation levels near Europa", "Fuel limitations only", "Communication blackouts"], a: "Extremely high radiation levels near Europa", d: "Martian", c: "ESA" },
  { q: "What is the name of the ESA rover that was planned for the ExoMars program (now delayed/restructured)?", o: ["Curiosity", "Rosalind Franklin", "Perseverance", "Opportunity"], a: "Rosalind Franklin", d: "Martian", c: "ESA" },
  { q: "Which ESA spacecraft is currently providing high-resolution images of the Sun's poles for the first time?", o: ["SOHO", "Solar Orbiter", "Parker Solar Probe", "STIX"], a: "Solar Orbiter", d: "Martian", c: "ESA" },
  { q: "What is the approximate cruise duration of the JUICE mission from launch to Jupiter arrival?", o: ["3 years", "5 years", "8 years", "12 years"], a: "8 years", d: "Martian", c: "ESA" },

  // ========== Telescopes ==========

  // Earthbound
  { q: "What does JWST stand for?", o: ["James Webb Space Telescope", "Joint Wide-field Space Telescope", "Jupiter Wide Survey Telescope", "Just Watching Space Things"], a: "James Webb Space Telescope", d: "Earthbound", c: "Telescopes" },
  { q: "Which space telescope is famous for its deep-field images and has been operating since 1990?", o: ["Chandra", "Hubble Space Telescope", "Spitzer", "Kepler"], a: "Hubble Space Telescope", d: "Earthbound", c: "Telescopes" },
  { q: "What is the name of NASA's next major flagship space telescope launching in August 2026?", o: ["Nancy Grace Roman Space Telescope", "Habitable Worlds Observatory", "LUVOIR", "Origins Space Telescope"], a: "Nancy Grace Roman Space Telescope", d: "Earthbound", c: "Telescopes" },
  { q: "Where is the Vera C. Rubin Observatory located?", o: ["Hawaii", "Chile", "Canary Islands", "Arizona"], a: "Chile", d: "Earthbound", c: "Telescopes" },
  { q: "What is the primary mirror diameter of the James Webb Space Telescope?", o: ["2.4 meters", "6.5 meters", "8.4 meters", "10 meters"], a: "6.5 meters", d: "Earthbound", c: "Telescopes" },
  { q: "Which telescope is designed to survey the entire southern sky every few nights for 10 years?", o: ["Hubble", "JWST", "Vera C. Rubin Observatory", "Keck"], a: "Vera C. Rubin Observatory", d: "Earthbound", c: "Telescopes" },
  { q: "What type of light does the James Webb Space Telescope primarily observe?", o: ["X-ray", "Ultraviolet", "Infrared", "Radio"], a: "Infrared", d: "Earthbound", c: "Telescopes" },
  { q: "Which famous astronomer is the Nancy Grace Roman Space Telescope named after?", o: ["Vera Rubin", "Nancy Grace Roman, NASA's first Chief of Astronomy", "Henrietta Leavitt", "Caroline Herschel"], a: "Nancy Grace Roman, NASA's first Chief of Astronomy", d: "Earthbound", c: "Telescopes" },
  { q: "What is the name of the world's largest digital camera, currently operating at the Vera C. Rubin Observatory?", o: ["LSST Camera", "Wide Field Instrument", "NIRCam", "ACS"], a: "LSST Camera", d: "Earthbound", c: "Telescopes" },
  { q: "Which space telescope was specifically designed to hunt for exoplanets by watching for transits?", o: ["Hubble", "Kepler / TESS", "Chandra", "Spitzer"], a: "Kepler / TESS", d: "Earthbound", c: "Telescopes" },

  // Orbit
  { q: "In what year did the Vera C. Rubin Observatory officially begin its 10-year Legacy Survey of Space and Time?", o: ["2024", "2025", "2026", "2027"], a: "2026", d: "Orbit", c: "Telescopes" },
  { q: "What is the approximate size of the primary mirror of the Vera C. Rubin Observatory's Simonyi Survey Telescope?", o: ["3.5 meters", "6.5 meters", "8.4 meters", "10 meters"], a: "8.4 meters", d: "Orbit", c: "Telescopes" },
  { q: "Where will the Nancy Grace Roman Space Telescope operate once launched?", o: ["Low Earth orbit", "Geostationary orbit", "Earth-Sun L2 Lagrange point", "Lunar orbit"], a: "Earth-Sun L2 Lagrange point", d: "Orbit", c: "Telescopes" },
  { q: "What is one of the main science goals of the Roman Space Telescope?", o: ["Only studying the Sun", "Understanding dark energy and discovering thousands of exoplanets", "Mapping the surface of Mars", "Observing only radio sources"], a: "Understanding dark energy and discovering thousands of exoplanets", d: "Orbit", c: "Telescopes" },
  { q: "How many megapixels does the camera on the Vera C. Rubin Observatory have?", o: ["100 megapixels", "1,000 megapixels", "3,200 megapixels", "10,000 megapixels"], a: "3,200 megapixels", d: "Orbit", c: "Telescopes" },
  { q: "Which telescope is currently the most powerful infrared observatory in space?", o: ["Hubble", "Spitzer", "James Webb Space Telescope", "Herschel"], a: "James Webb Space Telescope", d: "Orbit", c: "Telescopes" },
  { q: "What is the name of the coronagraph instrument on the Roman Space Telescope that will enable direct imaging of exoplanets?", o: ["NIRCam", "Coronagraph Instrument (CGI)", "MIRI", "NIRSpec"], a: "Coronagraph Instrument (CGI)", d: "Orbit", c: "Telescopes" },
  { q: "Which ground-based telescope under construction in Chile will have a 39-meter primary mirror?", o: ["Vera C. Rubin Observatory", "Extremely Large Telescope (ELT)", "Giant Magellan Telescope", "Thirty Meter Telescope"], a: "Extremely Large Telescope (ELT)", d: "Orbit", c: "Telescopes" },
  { q: "How often does the Vera C. Rubin Observatory plan to image the entire visible southern sky during its survey?", o: ["Once per year", "Every few nights", "Once per month", "Only once"], a: "Every few nights", d: "Orbit", c: "Telescopes" },
  { q: "Which space telescope discovered the majority of the confirmed exoplanets known before the TESS and Kepler eras ended?", o: ["Hubble", "Kepler", "Spitzer", "Chandra"], a: "Kepler", d: "Orbit", c: "Telescopes" },

  // Martian
  { q: "What is the planned launch vehicle for the Nancy Grace Roman Space Telescope in August 2026?", o: ["SLS", "Falcon Heavy", "Ariane 6", "New Glenn"], a: "Falcon Heavy", d: "Martian", c: "Telescopes" },
  { q: "Approximately how much data is the Vera C. Rubin Observatory expected to generate each night during its survey?", o: ["100 GB", "1 TB", "Around 10 TB", "100 TB"], a: "Around 10 TB", d: "Martian", c: "Telescopes" },
  { q: "What is the field of view advantage of the Roman Space Telescope's Wide Field Instrument compared to Hubble?", o: ["About the same", "Roughly 100 times larger", "10 times smaller", "Only slightly larger"], a: "Roughly 100 times larger", d: "Martian", c: "Telescopes" },
  { q: "Which telescope is designed to detect millions of transient events (supernovae, asteroids, variable stars) every night through its alert system?", o: ["JWST", "Hubble", "Vera C. Rubin Observatory", "Roman"], a: "Vera C. Rubin Observatory", d: "Martian", c: "Telescopes" },
  { q: "What is the approximate wavelength range the James Webb Space Telescope can observe?", o: ["Only visible light", "0.6 to 28.5 microns (near to mid-infrared)", "Only X-rays", "Radio waves only"], a: "0.6 to 28.5 microns (near to mid-infrared)", d: "Martian", c: "Telescopes" },
  { q: "Which future space telescope concept is often discussed as the successor focused on characterizing Earth-like exoplanets?", o: ["Roman", "Habitable Worlds Observatory", "Euclid", "PLATO"], a: "Habitable Worlds Observatory", d: "Martian", c: "Telescopes" },
  { q: "What is the name of the 3.2-gigapixel camera's survey mode that allows Rubin to cover huge areas of sky quickly?", o: ["Deep Field Mode", "Wide-Fast-Deep survey strategy", "Staring Mode", "Spectroscopic Mode"], a: "Wide-Fast-Deep survey strategy", d: "Martian", c: "Telescopes" },
  { q: "How many individual hexagonal mirror segments make up the primary mirror of the James Webb Space Telescope?", o: ["7", "18", "36", "54"], a: "18", d: "Martian", c: "Telescopes" },
  { q: "Which telescope's data is expected to discover more asteroids and near-Earth objects than all previous surveys combined?", o: ["Pan-STARRS", "Vera C. Rubin Observatory", "Catalina Sky Survey", "ATLAS"], a: "Vera C. Rubin Observatory", d: "Martian", c: "Telescopes" },
  { q: "What is the expected primary science lifetime of the Nancy Grace Roman Space Telescope?", o: ["2 years", "5 years (with possible extension)", "15 years", "30 years"], a: "5 years (with possible extension)", d: "Martian", c: "Telescopes" },

  // ========== Astronauts ==========

  // Earthbound
  { q: "Who was the first human to walk on the Moon?", o: ["Buzz Aldrin", "Neil Armstrong", "Michael Collins", "Yuri Gagarin"], a: "Neil Armstrong", d: "Earthbound", c: "Astronauts" },
  { q: "Which country put the first human into space?", o: ["United States", "Soviet Union", "China", "France"], a: "Soviet Union", d: "Earthbound", c: "Astronauts" },
  { q: "What is the name of the first American woman in space?", o: ["Sally Ride", "Mae Jemison", "Judy Resnik", "Christa McAuliffe"], a: "Sally Ride", d: "Earthbound", c: "Astronauts" },
  { q: "Which astronaut commanded the Artemis II mission around the Moon in 2026?", o: ["Victor Glover", "Reid Wiseman", "Christina Koch", "Randy Bresnik"], a: "Reid Wiseman", d: "Earthbound", c: "Astronauts" },
  { q: "Who became the first woman to travel to the Moon (flyby) on Artemis II?", o: ["Christina Koch", "Jessica Meir", "Anne McClain", "Kayla Barron"], a: "Christina Koch", d: "Earthbound", c: "Astronauts" },
  { q: "Which astronaut became the first Black person to travel to the Moon on Artemis II?", o: ["Victor Glover", "Leland Melvin", "Bernard Harris", "Robert Satcher"], a: "Victor Glover", d: "Earthbound", c: "Astronauts" },
  { q: "What is the name of the Canadian astronaut who flew on Artemis II?", o: ["Chris Hadfield", "Jeremy Hansen", "David Saint-Jacques", "Julie Payette"], a: "Jeremy Hansen", d: "Earthbound", c: "Astronauts" },
  { q: "Which NASA astronaut holds the record for the most cumulative time spent in space by an American (as of 2026)?", o: ["Peggy Whitson", "Christina Koch", "Scott Kelly", "Mark Vande Hei"], a: "Peggy Whitson", d: "Earthbound", c: "Astronauts" },
  { q: "What does ISS stand for?", o: ["International Space Station", "Interplanetary Space System", "Integrated Satellite Station", "International Science Satellite"], a: "International Space Station", d: "Earthbound", c: "Astronauts" },
  { q: "Which spacecraft currently carries NASA astronauts to the International Space Station under the Commercial Crew Program?", o: ["Orion only", "SpaceX Dragon and Boeing Starliner", "Soyuz only", "New Shepard"], a: "SpaceX Dragon and Boeing Starliner", d: "Earthbound", c: "Astronauts" },

  // Orbit
  { q: "Who is the commander of the Artemis III crew announced in 2026?", o: ["Reid Wiseman", "Randy Bresnik", "Victor Glover", "Frank Rubio"], a: "Randy Bresnik", d: "Orbit", c: "Astronauts" },
  { q: "Which European astronaut is scheduled to serve as pilot on Artemis III?", o: ["Thomas Pesquet", "Luca Parmitano", "Alexander Gerst", "Samantha Cristoforetti"], a: "Luca Parmitano", d: "Orbit", c: "Astronauts" },
  { q: "What historic first did Christina Koch achieve on Artemis II?", o: ["First woman to perform a spacewalk", "First woman to travel to the Moon", "First woman to command the ISS", "First woman to fly on a commercial crew mission"], a: "First woman to travel to the Moon", d: "Orbit", c: "Astronauts" },
  { q: "Which astronaut set the record for the longest single spaceflight by a woman?", o: ["Peggy Whitson", "Christina Koch", "Sunita Williams", "Shannon Lucid"], a: "Christina Koch", d: "Orbit", c: "Astronauts" },
  { q: "What is the name of the Russian spacecraft that has transported crews to the ISS for decades?", o: ["Progress", "Soyuz", "Shenzhou", "Tianzhou"], a: "Soyuz", d: "Orbit", c: "Astronauts" },
  { q: "Which NASA astronaut spent 355 consecutive days on the ISS, setting a U.S. single-flight record?", o: ["Scott Kelly", "Mark Vande Hei", "Peggy Whitson", "Frank Rubio"], a: "Frank Rubio", d: "Orbit", c: "Astronauts" },
  { q: "What is the typical duration of a standard long-duration ISS expedition?", o: ["2 weeks", "About 6 months", "1 year exactly", "2 years"], a: "About 6 months", d: "Orbit", c: "Astronauts" },
  { q: "Which astronaut was the first person of African descent to perform a spacewalk?", o: ["Guion Bluford", "Bernard Harris", "Robert Satcher", "Victor Glover"], a: "Bernard Harris", d: "Orbit", c: "Astronauts" },
  { q: "What is the name of China's crewed spacecraft?", o: ["Soyuz", "Shenzhou", "Tianzhou", "Dragon"], a: "Shenzhou", d: "Orbit", c: "Astronauts" },
  { q: "Which Artemis II crew member was the first non-American to travel beyond low Earth orbit to the Moon?", o: ["Victor Glover", "Christina Koch", "Jeremy Hansen", "Reid Wiseman"], a: "Jeremy Hansen", d: "Orbit", c: "Astronauts" },

  // Martian
  { q: "As of 2026, who holds the record for the most total time spent in space by any human?", o: ["Gennady Padalka", "Yuri Malenchenko", "Oleg Kononenko", "Peggy Whitson"], a: "Oleg Kononenko", d: "Martian", c: "Astronauts" },
  { q: "Which two astronauts completed the first all-female spacewalk in 2019?", o: ["Christina Koch and Jessica Meir", "Peggy Whitson and Sunita Williams", "Sally Ride and Kathryn Sullivan", "Anne McClain and Christina Koch"], a: "Christina Koch and Jessica Meir", d: "Martian", c: "Astronauts" },
  { q: "What is the name of the backup crew member assigned for Artemis III?", o: ["Andre Douglas", "Bob Hines", "Jenni Gibbons", "Victor Glover"], a: "Bob Hines", d: "Martian", c: "Astronauts" },
  { q: "Which NASA astronaut flew on both the Space Shuttle and later commanded an ISS expedition, and is now Artemis III commander?", o: ["Randy Bresnik", "Reid Wiseman", "Barry Wilmore", "Terry Virts"], a: "Randy Bresnik", d: "Martian", c: "Astronauts" },
  { q: "What is the approximate number of people who have flown to space as of mid-2026?", o: ["Around 400", "Around 700", "Over 1,000", "Around 300"], a: "Around 700", d: "Martian", c: "Astronauts" },
  { q: "Which Chinese astronaut became the first woman to live aboard the Tiangong space station for a long-duration mission?", o: ["Liu Yang", "Wang Yaping", "Nie Haisheng", "Zhang Yuzhuo"], a: "Wang Yaping", d: "Martian", c: "Astronauts" },
  { q: "What is the name of the NASA program that selected the first group of astronauts in 1959?", o: ["Mercury Seven", "New Nine", "Original Sixteen", "Mercury Thirteen"], a: "Mercury Seven", d: "Martian", c: "Astronauts" },
  { q: "Which astronaut performed the first untethered spacewalk using the Manned Maneuvering Unit?", o: ["Bruce McCandless", "Ed White", "Alexei Leonov", "Story Musgrave"], a: "Bruce McCandless", d: "Martian", c: "Astronauts" },
  { q: "What is the record for the farthest distance any human has traveled from Earth (set by Artemis II)?", o: ["About 240,000 miles", "About 252,756 miles", "About 280,000 miles", "About 400,000 miles"], a: "About 252,756 miles", d: "Martian", c: "Astronauts" },
  { q: "Which two crew members on Artemis III are mission specialists alongside Randy Bresnik and Luca Parmitano?", o: ["Frank Rubio and Andre Douglas", "Victor Glover and Christina Koch", "Reid Wiseman and Jeremy Hansen", "Bob Hines and Jenni Gibbons"], a: "Frank Rubio and Andre Douglas", d: "Martian", c: "Astronauts" },

  // ========== Physics ==========

  // Earthbound
  { q: "What is the primary force that keeps planets and spacecraft in orbit?", o: ["Magnetism", "Gravity", "Solar wind", "Centrifugal force only"], a: "Gravity", d: "Earthbound", c: "Physics" },
  { q: "What does \"delta-v\" measure in spaceflight?", o: ["The change in velocity a spacecraft needs", "The diameter of the rocket", "The daily fuel consumption", "The distance to the target"], a: "The change in velocity a spacecraft needs", d: "Earthbound", c: "Physics" },
  { q: "What is the shape of most planetary orbits according to Kepler's first law?", o: ["Perfect circles", "Ellipses", "Parabolas", "Squares"], a: "Ellipses", d: "Earthbound", c: "Physics" },
  { q: "What is the common name for the speed needed to completely escape a planet's gravitational pull?", o: ["Orbital velocity", "Escape velocity", "Terminal velocity", "Cruise speed"], a: "Escape velocity", d: "Earthbound", c: "Physics" },
  { q: "What causes astronauts to experience weightlessness in orbit?", o: ["There is no gravity in space", "They are in continuous free fall around the Earth", "The spacecraft cancels gravity", "Magnetic fields"], a: "They are in continuous free fall around the Earth", d: "Earthbound", c: "Physics" },
  { q: "What is the main reason rockets are staged (use multiple stages)?", o: ["To look more impressive", "To discard empty tanks and engines, improving efficiency", "To carry more astronauts", "To reduce cost only"], a: "To discard empty tanks and engines, improving efficiency", d: "Earthbound", c: "Physics" },
  { q: "What is the approximate escape velocity from Earth's surface?", o: ["7.9 km/s", "11.2 km/s", "15 km/s", "3 km/s"], a: "11.2 km/s", d: "Earthbound", c: "Physics" },
  { q: "What type of orbit stays fixed over the same point on the equator?", o: ["Low Earth orbit", "Polar orbit", "Geostationary orbit", "Sun-synchronous orbit"], a: "Geostationary orbit", d: "Earthbound", c: "Physics" },
  { q: "What is the primary source of radiation danger for astronauts beyond low Earth orbit?", o: ["Only ultraviolet light", "Galactic cosmic rays and solar particle events", "Earth's magnetic field", "Radio waves"], a: "Galactic cosmic rays and solar particle events", d: "Earthbound", c: "Physics" },
  { q: "What does ISP (specific impulse) measure for a rocket engine?", o: ["Thrust only", "How efficiently it uses propellant", "Nozzle size", "Combustion temperature only"], a: "How efficiently it uses propellant", d: "Earthbound", c: "Physics" },

  // Orbit
  { q: "What is a Hohmann transfer orbit commonly used for?", o: ["Landing on the Moon", "The most fuel-efficient way to transfer between two circular orbits", "Escaping the solar system", "Entering the atmosphere"], a: "The most fuel-efficient way to transfer between two circular orbits", d: "Orbit", c: "Physics" },
  { q: "Why do spacecraft in low Earth orbit eventually reenter the atmosphere if not reboosted?", o: ["Gravity increases", "Atmospheric drag slowly reduces their orbital energy", "The Moon pulls them down", "Solar pressure"], a: "Atmospheric drag slowly reduces their orbital energy", d: "Orbit", c: "Physics" },
  { q: "What is the approximate orbital speed of the International Space Station?", o: ["3 km/s", "7.7 km/s", "11 km/s", "15 km/s"], a: "7.7 km/s", d: "Orbit", c: "Physics" },
  { q: "What is the main advantage of a polar orbit for Earth observation satellites?", o: ["It stays over the equator", "It allows the satellite to eventually see the entire surface of the Earth", "It requires less fuel", "It is closer to the Moon"], a: "It allows the satellite to eventually see the entire surface of the Earth", d: "Orbit", c: "Physics" },
  { q: "What happens to a spacecraft's orbital period when its altitude increases?", o: ["It gets shorter", "It gets longer", "It stays the same", "It becomes unpredictable"], a: "It gets longer", d: "Orbit", c: "Physics" },
  { q: "What is the primary reason nuclear thermal propulsion offers higher performance than chemical rockets?", o: ["It uses no propellant", "It achieves much higher exhaust velocities (higher specific impulse)", "It is lighter", "It works better in atmosphere"], a: "It achieves much higher exhaust velocities (higher specific impulse)", d: "Orbit", c: "Physics" },
  { q: "What is the name of the point where the gravitational forces of two bodies (like Earth and Moon) balance?", o: ["Lagrange point", "Apogee", "Perigee", "Node"], a: "Lagrange point", d: "Orbit", c: "Physics" },
  { q: "Why is it more efficient to launch rockets near the equator for most missions?", o: ["The atmosphere is thinner", "The Earth's rotational speed gives a free boost in velocity", "It is closer to space", "Less gravity"], a: "The Earth's rotational speed gives a free boost in velocity", d: "Orbit", c: "Physics" },
  { q: "What is the approximate delta-v required to go from low Earth orbit to a trans-Mars injection?", o: ["About 1 km/s", "About 3.6–4 km/s", "About 8 km/s", "About 12 km/s"], a: "About 3.6–4 km/s", d: "Orbit", c: "Physics" },
  { q: "What causes the \"slingshot\" or gravity-assist effect used by spacecraft?", o: ["Magnetic fields", "Exchanging momentum with a planet as the spacecraft flies by", "Solar sails", "Atmospheric bounce"], a: "Exchanging momentum with a planet as the spacecraft flies by", d: "Orbit", c: "Physics" },

  // Martian
  { q: "What is the approximate specific impulse range of a modern high-performance chemical rocket engine (LOX/LH2)?", o: ["150–200 seconds", "300–450 seconds", "800–1,000 seconds", "2,000+ seconds"], a: "300–450 seconds", d: "Martian", c: "Physics" },
  { q: "What is the main limitation of ion thrusters despite their very high specific impulse?", o: ["They produce very low thrust", "They only work on Earth", "They require no electricity", "They use too much propellant"], a: "They produce very low thrust", d: "Martian", c: "Physics" },
  { q: "What is the name of the effect where a spacecraft's orbit slowly rotates due to the Earth's equatorial bulge?", o: ["Nodal precession", "Apsidal precession", "Frame dragging", "Poynting-Robertson effect"], a: "Nodal precession", d: "Martian", c: "Physics" },
  { q: "Why do solar sails accelerate continuously even though the force is tiny?", o: ["They have no mass", "Photon pressure provides continuous low thrust with no propellant", "They use magnetic fields", "They harvest atmospheric particles"], a: "Photon pressure provides continuous low thrust with no propellant", d: "Martian", c: "Physics" },
  { q: "What is the approximate delta-v required for a soft landing on the Moon from low lunar orbit?", o: ["About 0.5 km/s", "About 1.6–2 km/s", "About 4 km/s", "About 8 km/s"], a: "About 1.6–2 km/s", d: "Martian", c: "Physics" },
  { q: "What is the primary reason the Van Allen radiation belts make certain orbits more hazardous?", o: ["They contain high-energy charged particles trapped by Earth's magnetic field", "They are very cold", "They block radio signals completely", "They have strong winds"], a: "They contain high-energy charged particles trapped by Earth's magnetic field", d: "Martian", c: "Physics" },
  { q: "What is the Oberth effect in rocketry?", o: ["Thrust is more effective when the rocket is moving faster (deeper in a gravity well)", "Engines work better in vacuum only", "Fuel is denser at higher altitudes", "Nozzles expand more in space"], a: "Thrust is more effective when the rocket is moving faster (deeper in a gravity well)", d: "Martian", c: "Physics" },
  { q: "What is the approximate surface gravity of Mars compared to Earth?", o: ["About the same", "About 38% of Earth's", "About 10% of Earth's", "About 90% of Earth's"], a: "About 38% of Earth's", d: "Martian", c: "Physics" },
  { q: "Why is a bi-elliptic transfer sometimes more efficient than a Hohmann transfer for large orbital changes?", o: ["It uses less time", "For very large radius changes, the total delta-v can be lower", "It requires no gravity assists", "It only works with ion engines"], a: "For very large radius changes, the total delta-v can be lower", d: "Martian", c: "Physics" },
  { q: "What is the main physical reason that heat shields are required for atmospheric entry?", o: ["To generate lift", "To protect the spacecraft from the extreme heat created by compressing and frictionally heating the atmosphere at high speed", "To reflect radio signals", "To store fuel"], a: "To protect the spacecraft from the extreme heat created by compressing and frictionally heating the atmosphere at high speed", d: "Martian", c: "Physics" },
];
